apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: tubesync
    namespace: tubesync
spec:
    interval: 15m
    chart:
        spec:
            chart: tubesync
            version: 6.0.9
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: tubesync
    values:
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            tubesync:
                name: tubesync
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        ingress:
            main:
                enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /config
                readOnly: false
                size: 8Gi
                storageClass: ""
            downloads:
                autoPermissions:
                    enabled: false
                enabled: true
                medium: ""
                mountPath: /downloads
                readOnly: false
                type: emptyDir
            data-vol:
                enabled: true
                type: nfs
                mountPath: /data/media/youtube/
                path: /mnt/PoolTwo/data/media/youtube/
                server: ${MEDIA_LOCAL_NAS_IP}
            varrun:
                enabled: false
        release_name: tubesync
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: ${MEDIA_GROUP}
                runAsUser: ${MEDIA_USER}
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: ""
                ports:
                    main:
                        port: 4848
                        protocol: tcp
                        targetPort: 4848
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                DATABASE_CONNECTION: ""
                                HTTP_PASS: ""
                                HTTP_USER: ""
                                TUBESYNC_DEBUG: "True"
                                TUBESYNC_HOSTS: ""
                                TUBESYNC_WORKERS: "4"
                                http_PASS: ""
                                http_USER: ""
                replicas: 1
                type: Deployment
