apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:giHsFVgD+y7xiIVYSt2crasGVVIGCGkTzLDAaXWDwoebEZrSZpBOxkt7SOsvsfx8T1jzA75WZUdEsc21zsinc0KuaqF8nRioVjjQnRZRS7d8PPgfQdUOR8qOp1/H6TINYrgGqgOrQ/RaWN7r0m8zCf/HLVqToRanGi8o05o43mUNS3IMkdWWYQAY4wTkNkQKKbf7zVuqZB4/JUNPpw1PABTpHgs2TXDZiU86FswCiSK2kk7oYdZbl6KDOGVmNV5dv++4U9I7E/03rcTThVFyxAJT6ZHmJnAuSSoOEeKnnWqMnhQDk2lxbo1oHtVMzBFL/Kn3tH34Xp12SkbWTL6x2kLewcomwNikNe7u6AwJ8LmpPeuMq7Wz/xKoHvvtHH/n,iv:S8lsEJY54cuojrjYIGJxTq5cXgKFM2WhD6EOvL8mCEE=,tag:7oDE5J9FM990SJ0yl5kDOQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:goKY/QYoBMr7fbJYDKx0SUCZc6xlfpz5DxGUYRcXc2FGC3XYQ/T114rF5pnjGShj7jj+fZU5slXzhvXL3+iLmCJpnuuLchuIWV5ngl3uKQmpF3Zpr1DDek9yuNCpDsl1fe0Gmr36grFa7UTz0TRRkL9YfwQSnsrW0SJeTcZ7jXqmaEroHFHmXU415v+uoMWrA27yM/KrViIIBpU8iM6RoAt0kyKK/6M+Kc1C71XfiDbErFeJNki+YuWbbhNfl5OdA9GNgsDlkqI9+Ga0GQ==,iv:+Fpriib9KNyqlqJdM37pAUvRJZxxTM3HYjlfFUdus58=,tag:8ZHzfRayzREM0qbkFOTbOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:kg0vENtJr5q5pYH4/gIrE7SwHR+rdP6ASHtbEKENOc19UPhkApyQ+O2r5iAcYo12tn8gNGcNyEE4N/Co7CYIXNyXzT5U2GKNgrIlDY7H06yoIygZw4EiVKBBNPNem77sB7xSNevRNVPeE4Icp9lWwsmDjy7kQLy900CwPMUYGvljV+vUK9tJdciinHQNIcG84eLI7z3N2Ivg0kTFVLWMkU2TX85lVxb2CfsR,iv:assBClmAzkttY6Pzc2pE4uE/CsqiDeTjkVvdxV5flmo=,tag:JXrqqTugomYv4XawRG1fmA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMHhwS0N2TkNJeExEU2ZI
            dWNRWERRczlzcVR0MlAzeU9yWU1lM1o0aURvClg1VGpXcm9pK1gwdnBLS3QwZ3Jp
            M2k5RjMzZWM5WEU3NWdqVzFxZHZaRlUKLS0tIGFaRGk0NmpWdkYwY3U1cmUrcmJJ
            Z0M1azJBRlRtUXdLVlpvdlhDT3U3L1UK+13eCj1F9YtfjOtohkyyrL2XvpaDker9
            ZMunzEuDCX93INhdb2+155aATWNqLHjYtrxzwpsRuttvYaLazTt9GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T22:10:37Z"
    mac: ENC[AES256_GCM,data:Wmj9PSx8rqgSX572AfoFQeiMaGnJEALgCjvQHZiCS+rHlnVzoYBzeMEnDHybbeowvymAzeEF8hdU81us1tNiGh3Nq8TNYC4/tNYax/qTEd4T9ExWrcKUZJXa19CW21icNkiUHhWRlefU5ObfUM1z+1k7eo16nPsQMqXE70WPT9o=,iv:uo6PuN+nX0/0nduc2iJBweNDTlKfkcWlWkcjsRID2O4=,tag:50XP0OXeAfPR43Mz8GGPig==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
