apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:v9yuM30WO0+wz7PQhQ04iQxhwy0/LfneWfaf8b+KWQuMzEXTSw4HIKp3XtK98qKc84Gm9QKSX0JHsNqnYKuarqlgWyHPO3lxCRtU6m/C1gcJYXP1qLcrht74u6FC9Gi9g6u3k8XFbFDxBmQO2KuHIFtG1nmkItV4l/sPCcCNgjpbEMVH9hD8FNdqYTzAYDUMRhQ2IR3o6ebwwFeXoB6YNkILi4FZPMpUj9KdIC9lSlVEzeooKkNAylp5xNCanIR+SVKfa/B9losx80oH0Z+v4kWfY1dY0AUAUrFc7UEMHEwbbfKk3aDVLuomLo8ZZbUh0GJo/RK1A+5jZCbs2cXw/B0lpavnT52AGb+QMwaTupB2cOWrBaP9iSacoGqTMgCa,iv:4OtwzCIa9dugf1gLVualUwq6nGnc11vOwpPzw0WdwjQ=,tag:HkZ52I4u0GlCUH4PAxtEDg==,type:str]
    identity.pub: ENC[AES256_GCM,data:9No4xvQTMeqxBs96hP2N61hpJmsiYQQHNISd7Ot1j1bcU251nhy0dlrQKhk4Z0UWLWjRKl4TSGI2Z86qokHTIQLK0kIoVEiPi1Q+Iy0ccAo/Msh9zGmgziQ33Iyb9NwHikewbfpk2eO3WIUy0NB7wik+Vg4rUlrZVZZQiFr+POSCASSsK21t6QtVyjU5VNSjJ3eL7NuoftGWs7Di3Y3YyRdQtP/vpRb9ieyysOUuk770WIvJpI1U50apcCXR96oWh1VXfbvOkd/6u6/6zg==,iv:m8C41Pe+bmYB7mX4/P/crtus8wZD0Fisjiab66o1BoI=,tag:e8BgYw25Fo+2W5E0l6XVrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xgvgZXJnavJzDEH0tYAa7PaCcPN+l2ITyIZRKSTKNioYIqJr197ybA4CY9FbEMQuOldOeHbqLNpuCOgqE6ENSvDqEUaWInXcKqtk96DV9/3YuJ7/2Qi1SFqQ2oGiuXO9p3bM6UmBAM1hcH9jbJOqVbQ3pFSIQNo1IsWw2lWvSOcb1rXgaMsgGFAyl6SXR+ENlr/lWFLcMYbi9ZazjvaakE2awSC4e3XcG8w1,iv:nTzS6k/GWvoNhBQN7M0xoTKUxfgcsjK/lzL/oFLLgS4=,tag:8XukBgfAd6FVs0MZqU8iog==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUkllOEtFL25JU3hNSWps
            cnlpNlU5MWVsL21JYnFRc054OVhGZjVocDNnCkVrbXVCWmtCR3lxdjk1NEFFSkM4
            ZnVhNTFlbnJ2aUp6Nm5KY1RoRzBoTWcKLS0tIE9jVGVuZXZiTFNFRnRTUXhtQ0Qx
            VjJQT01LNG4yZ1VTMFFSNTZSZXdLZlkKoZLUl/mODmGyTB4SNqix2BBUayyS4yJl
            M3rFU1+F0aP1NVrT0B8ixejfRTXK2L/512UzHHtkyNQTtehZX6BVUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T02:26:25Z"
    mac: ENC[AES256_GCM,data:LTyJOqG+kks3MX6A+naZznLnxMK8H22MYMhHt7imugbqBDYQnOjLufI2nYkuJqOTCj1GcpxuKXlo0yawWdd9VtytoFPXsT1zU9feokWVGUwRF4cX1gOCixEL3vKiGsmCWnyvPAun+I4rSQbkLm8vQUk+oZTL9m/w8mfVYm4RIO0=,iv:dD/S6+M/1lWOik6a79YBOcn0gqS9Y3/MJhI31Qr/4SE=,tag:ip54FZRNWQCwqAAlL+CrHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
