apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e6pikI2XSt4sLJXts6XfAd3hy9zr+Lx+g+77/4PzV7z4KTK/BAJJeJx0G8V2DvDlTqP71Y178SnmVCln6TywjpqfYyfty/2ITcNh32QLwcOY2IiWDuYBoJ2dlsRrNOSb4BlizL9nuXXcxGvBUqpp+t/Pg8xKyik3fZgCtCRq9f4JzTl299FAEIW+43dEaxh3jNLJhoGfQr8xAPVqLpWEndD/ttNhTirEc39zNBqHWDVIypa+jsqQDg222mJi7vQk8CFLRlE+Ydl8JxOnPAfrb1F2E8djwblbQ6YVcOtULzGMyCWdFDxraUv/1mZeSP935dPOjZhrun3PIE9xKnXdkWUgm0ZWvEVLobT6v67ztbSf3D967/S8kFExdQgeVYtK,iv:uFNh8V+KABsWWjz5QZ6bHE3rFvfo8+2/A9U+xJoxKbo=,tag:JyIwqepk9BeJkhSFt+H8aQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:019UwdkVSmA+6wG9BO/6+b3npMr+zgRFULK6o4aETBvYmmcRpH53I/bB1t1q56cLD0q6fdG4APA4zvb+nqfBwS4RN8i99I7eJ5eEo5Y/T6+fKIU4MwKWhqG1RzjYzZ+0NJgg9n85Ha1C80HvLtCAuOkCHjDVkqymzdJs17HTpd1QmzwA2torE0Hq0QsEe248EP/VZdYIRtkOWmcPUYr3tRgMH06ts7GhENCit/lBT35TahXBCEkIF30lM0dE0eEoac0rh1eYgCYg+kw+ig==,iv:bhLDOGKGEEKD5WaUIqAl/1j63hLEAEgrB5v3cnHHNYo=,tag:ELZuBXAH6ZHUcoHoWVOOEA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y2KtuLk+wF/etYWbqcySHOEuzMsbDg028MC6HCyfiPbjlkUZcwK6bCfaJfZc/q819vU2YfEKgtBX4qyQE5pShMRUy3W/XJwtI109ySYgzjHH5cyMMfhrjkq4bE+f0Dz2B3oAbnnifMkxwkNgXpRWXvoatLZlGKR2wx1rTRhOrC8JgWZgg0hmuLXmqRFUYmJkL4Jf746bR3v3FP3wxn92LQjA7cGQqCr+od1/,iv:uco/In4spZDuWaS59UEChgqP87sbJB+VCH1Y7pcVUwg=,tag:8XfVcZAccbHSuwcxPcQP3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZDl3SkNkdW9TLytQQmlt
            SFZMZjlXcUlDM2hhME9VQmRScjAyd3NVb2xFCkZMeXRZcHVqaS9VMUxmb1RXV3F5
            elQ0YmlnRG1ORG9scW1tRkJtNmsrbFEKLS0tIHMxS0doQ3pJTUpNcFVFNmlIVENU
            c21OZVFGZnRtMGJFbVlhSW1nNjVSNnMKBV9VFtpTj9ifm0UfT/4T/AaefisrlpCY
            1irun719NP5ikO2jHczPTys2mrwx91VMqpiG4ReS/4QlFFH+lhJWSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T07:28:14Z"
    mac: ENC[AES256_GCM,data:KdcGaKTlz3IaNVcXVPBiacKvkUAJJAG7NqNsIIR3Vx/crOZMfoPjkDNTKtqol2xDZyJPMt2jKi2RM69Rrre3LAME70DTfVnaqYI/ljJAVoiS9zn/CsRZiw/iacKfg5NcTQs1y2DLl4rrygl1bAfJkWDLFQfelDXQGDSP8Z+O2vA=,iv:5/2ao9dFgWREPtsFbQKIBVCjY+kB3cYyhcDtqOUfMfY=,tag:1oYc4yn7d1lQMHz23uZCnw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
