apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:pfaQfBuXksV5VAaO+k5MXvl3FGIWkNm032rfN6uYr2aa5quughn2++imih5Ca8GuvQOcVKMS1qjfs8yk6mPCtj0w0TyBadureGUyrIHuzzWubSAyq2dK7y0vAQkWfySXIfvu15m27GCpQ3pfMOee6DktvKzHPqaecpTkKyIXSJMCouoPvSuAbIWq9fILEcZUKs5+wLRK8Ha2qubyFBhIxgFl+kvLrclZizuy9eo5vbLid+V9YH84RiD3bI0Xm3zdsjGbEL6DmNnprQ3TPQIPYnm2jvHx/Jtg3+sAwWKlU1j0dp2gSzUUvoCFTx//4eOruk8Uo1zKK90MO5D/BW4LRgkPbUuTxXiT4GO4fyyqjaNDnVZaLC3IzuPOc03dPue0,iv:f2aRYQ9DgmcCFTtoqC2xCrRgZbeg8BMNRWGysIfW/0M=,tag:YfHjJDvpCUGv0iu0ErlSww==,type:str]
    identity.pub: ENC[AES256_GCM,data:kmzhSIHO2CpurCO9Yz+Elq8aCbBbN0x7gHozuqJrlIDzEwLlXfgfRIghiZFUIKi4aXe9VX4waMv9BoQQXzCiHBd4LyESXNDpxcihw+3N3Fi22nELKghe++gX/CnEilEa6pWHhA3lQ7gZbX/QOYJT46/PYPmdpMnmM9JT78+L8XbfX2qeEr90IR08TiF1RZV/maNQgZA5qkCD3Ig+Qphabe0KxyMHzhk5+yjrc9qq4XFMuDSUtedP7DJWQEs4ObsTLOr9yJgBALNhgP85jA==,iv:0lMY2Mij1SXkx7sS1cA71+DhVslvthg+OiGUs3Hb5dE=,tag:28CpOaUrys9lHryBn1X0+A==,type:str]
    known_hosts: ENC[AES256_GCM,data:pz3yVNHtAWi7qONvqBwqSW49cw8xewy+2DwujYzy8UsfG3dysKeL9jbRJxUInasD4q4fBq/Axnu0w70LbCPwkJ2gC+yA6hooP6unga/yfdM59LsYdvBkjQb9RzheGJjxc0dHuracrAaK7qXVkB0kIiRXstuFcARrTlm9YUWx29lYVqkltVaiHK+5E+b+DZpDlk/PtwrmPsyIHFD4AcLvWCWbU2Gu8pfH8QUz,iv:rk2w9j2E3J+RNxqW5UVFzxSaXc3nBpjCHxgQxsTfUWk=,tag:mqJIQ8aqgcNN94JM3KHmLA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT0FaTmRET1BiOEplUGhm
            UzJUSHRLTStXeHhxRzRUeDVvVGEwOFE1Rm5FCjFySmFVLzZMNG5TTnhIVGlEYlNU
            azNENXFVV2tQVUlVNWNWNWtsYjljWmsKLS0tIGtHejk3ZitHcTBpUXZIZzVMaVVH
            RE5WNGQ0R09veGtWZUpLM04xNnVSR1UKmdUd8+zxKTrhzihh9M1esm9gl6B3g6HY
            8/Snb6sbOwYeWfS9b+g+0pwySl/4mbWbAUZv9ZnhIQjMA9jWnxuCSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T02:03:12Z"
    mac: ENC[AES256_GCM,data:GpmimoQ52cK3i4hdqgdgfcVAm+cn3KTFUctmo2AdqvNUNkDYpDNZuYYvfthhpHV+Nz/azER0W5uWz47ETdDulM8XOZC3vNISPY/tQF5YxK7q69UhFFD2wNGETfZWXsX3bUrQ7fs15Yl7NsncOL4deZoTbhI3QM+ilyijzAO6OVk=,iv:o6PVoGCFKk34UKmc4GKxAm/9eha6kIlrq/6LjLVoFm0=,tag:YLyuIElX3Q+29sK0ziE5Ng==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
