apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TrRhHCGLlTHV69P7I9fExlGChXR6rDRC8KQS5Yj9B7Boi82wTJYz9aSYB3vYFoyTKExGnUL3aE7wqnRS5+anrCDJaku+zunY4PlEjGU0eXmm4ODWZW+PhScVxhCxxQhs3XnNjTBSwOyo1lAEgtinDXaXPcl8e9MgX4lQN838DCqO3LRHs2y3qoycxD7KicNcW9hnWHc7Rj/Ua5O36g8q/h6PiI8l1oc9eDHffOA91RatwHgwtDE78jOBzY8KPRAHgeJ38eVXmAI/+WL0LzQYkqIxs6hhJvdvRw5TRUlUMYJzb5suOO0/Ae3iD0tqSuLxQn/DSEEIizcuedH+LMGliRzBtjVWybXKX+yzRfEwxSLokCTPuiUJbQpT5/TKTkp2,iv:or0cEipIG7cwI5odCgTu/Pw06QcjHj/QSv5fmp08wnc=,tag:JLO0j4EL0WF9JxYfa0d7lw==,type:str]
    identity.pub: ENC[AES256_GCM,data:/FsTCslRDiQfCAcW1I1QaYmttbho81yg1VO/B9ZHCT6vED2CsVRheS3Z6RlkQz31qJ64okvdmJBi9V3v+krSVt/ugq0dRSh/7eDZUDxZv3kB+pg/3YhMde1VUie5zL7k4RCR4J50sLZ/GamI4QDb1HWjTa4OyqACOgY2GnpCyWhZfFeuQ/y6zSUKt5z/clf1+L2aXzLqS2enM7oZ6KB9f+ecazeDQzT33VmeJDo6Z8oseIvHbbZHXsMZLDtENRSvW+MgY3mZ0Y+Aa5c3MA==,iv:XCRetNBFyJ0YXm4t5z8gqM2SjXw4Tv5lJ+l7fUi/eZU=,tag:6mmP9LMhA91dKwVgkm8Now==,type:str]
    known_hosts: ENC[AES256_GCM,data:+pew7RSgP7qhexPeWS46J3R8lz75Juz6qjGfd/1kJaZ95KSB+jRs0Qj5u3adhaja3cJH0nfH0qX8unR4Jk8kNyrZDIZbivl7+CUdeTvQTRLJlGawVXxyEqiAOpYM8RcCEznCviH9BpRw12j6zDcHj43d/C3UQVokhJm38/fxemsfm96T+2L6XpQ72HLD9uZAbUFSJu7G7yxK9ShH8sHaLZInU/mhgBBuyj5f,iv:nIbZ1asASRCVkMnRlg9dIrOaWcwQ06MZ0EEryiNZZkM=,tag:pvOaBdFVVBymU5Z4Vc4UEQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K21oMHRCaTFHZkJadERO
            Rk0vS0pxWmtBZXJHNVNkNG5SYVgyVnFXOEFFClBmWEQwOGxHamQ4dUw2L3pBU1dy
            K1FoV2ErTUJuZHNpUURNVElYNWdodVUKLS0tIGVxeEltcmxZN2ZjcUhiMFNLYWNk
            ZXZJS1NlekQ5MXVsVmhlMVRSRjR5RXcKRPiTGZgQRvFDSoZr0WgRI/wgLnFwyCkY
            e62DAzP7578Fcjpo1VbxxQYc5FRNvaPkpVSjPQpbV4+A5TwZ6CU7Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T01:15:08Z"
    mac: ENC[AES256_GCM,data:qMWP6JtrJnPzHhYqX14YBYqOTx84pt+MSetvXFarxklDtdiu2iRHLYrW18QYK0f7o9dNZBZHEQoSJAM17u4Tc6b7mf7bUBnzAf5ty0ckjexTh88uaAchje/ZsIJpS6T1kgPDOpBAZhLZbBCO9ZuOIzwnsGpLpGRyhk1pBJFutcM=,iv:ihnnuRZ07D16kcsG2RhuY6N0Ju7XwNE6xoQ3ooZxctE=,tag:3CwkKbiK+b4V+7uujg3FuQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
