apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:W0Ick/YtBlb/6mz0GR5zyb0J6EyioXPIkXTvTVMq1AlsE380C43bSCPYh0Vf+go+gN/ZCfiV77jiEBWhaz8LAhFkYMerdGc6GATqHl/+8H+uS4pbw3KIrbpKYC9VF/jeLFbmDwopglgM1WjLGKlMorL4eSFeGSrCietqOinrb92v014QnBL0HSXSP9NJLnNgPrVufZlCjQ67Zv/1JkGsJMfNcNu7Kq+1FL+LIYZdXhPKZgMd3jQr+SNUZDNA3LAHAhmc01oUEDkZWemVnhz1KncqPMImrIqDdeRry6wP5maidzySqotAmW4lMNWTqJmYoJ4ICgF1F664frNmohWlFLBU3UHiGBfwBr7iKKy6AhgcqPqppRRN58zRM2V+f2zP,iv:8UEWHciTwpBa6Pct0KoHbfEjJk9ADWB2WIO/KDKcfN8=,tag:919MLxmAp4U6792hBXQzIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5S30rciKZOK2ClmbGj3SUdSpooYTDdXgbDKd8ClfJkw12/i9CXs4qS41HPjA7BuLmL+wyziHLit/wGF6WN/6+gzjH1MAcJAL4ElcmQoJFBLe/4K2ZC/+rbs4XhWV/kW60W576K6ke5MwgqtRpMmyQ8fC5td3jR39ic0wmoURklBgeAJG3w0zxxHGGjYMBWyR7Xg4MHgJ1ztwrjC558a5DrlEur4m/V503JMHuoyCL1CTEJduxaO0XDXndsij+61+wfoz7T3EbyIVDnS83A==,iv:XYAL+KLeVh2a4vOwohDBhLnx1cf5OMh/CC82xa9do/k=,tag:4TwqqX1uHC2EVk0MQequLw==,type:str]
    known_hosts: ENC[AES256_GCM,data:GVV8J/uhWt/bjEhO4LfiEzUs4dgOv+R1gRN6QdWTpXYPpT4lY4nviCI5iiOipzDURab49J+fc7JW2u5qmUjwpWktOvzBlOmBioyV9JN+3SbBDLW3aclK/pQ8hcBZytxfzZ6D2YNHrU+cunQJ4sP0RyuA8yJyzEItDH0yn1e5gORFXk8Tas5tJPqULr+SkenKtvYvKpBmHdw6ChuHvVx1z0QhmLtGutZDpZ7z,iv:MmXpW7LT1ik4WR6r1b0dM+ct7j/ZiG7m32jbn0trUAI=,tag:3/ujBOp74gs6SRuoXV0BXQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWFFYdkhXcEI4NklTUldw
            YmVHZHN4UytLWGlYMWNjblF5amNYQ2JaNHpJCkFJU0Q4Z05pUEtmME1PK1BJNFNH
            NkJWbWd2V0FVb081UmhpazduTzhXd2MKLS0tIEVENE5GM1BGdWJlNTBDZ3lobUtT
            QTFMQ0xmMXgvLzQvNmV2OUEvMTRVZUkK5MncwSiuM7Sao9XBYAVAiOp48tNZKZf7
            bUBahXnXsbty3R+YyKoQSFOLXfn7GM0gaPA1TLacI/YnU7gtwmRixw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T01:56:30Z"
    mac: ENC[AES256_GCM,data:DH+kNaikpOgneFT8BtaXGhKK9A4MfMsvZNASDqnh5lxYq4ChnMmxrrArgCPu1U30LG2JxMUcZoA86YM6hbo5aRoC40Km7zq14TeOP1iMM3XAosCAVSv+hbEzi7aVJfI73+gFLyqTiPTf27cHwkN3mZ5H3O2/QXkKRonB9oL45Hw=,iv:O34kslei0tIC1MMrflZ4ivskykjrq7xMga/omtWLybM=,tag:mD3uhVLUHtC6LWV3/+D9uw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
