apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ok7hfMEWtqEL5kFKRb8GwurTuzTHwS8cAULyXYmQYblsGY+tE6HI1KUy9Kw5MyxPYT8OGJopZMsun6Hkmdp38zf6PYz/SQwQHxFAkv0v9uUceGPLeDb3qRCsyQO8tGyMUG9oeH0rqjZOgz6oiso6qt6/Fn8c22CvIkChpPk0oN5O3d1T8T0IsrR/0bOokfNjqCOWUigoCKubf2TeSuKfyiSncMUi3wETH+66Y4D3twYYWQkc1b/5xvAsQ0YWBXhCFl3/BOhaKJXSmtIPIEU3A48k6AGws7z9WPuu0yHcRDzLxcMGPNOh7PFf9GKRfydfM+jSqIjVxZgNZ3weWrHUHluewZ+RzK8OR1WTrh+OrJST9taZ4qjNuoVkS0zNhtfQ,iv:u/+jcUuL7hCngRWQw7ybWG7bLPSuIz76alBgUzH+nk0=,tag:Er68dOpY8ocxORDK5MOgdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8jGxESUTcefMsXgQjNW5La2876fgyvSrIldTAdd8fcFNbsvXuCj4833y6dig+jZvwLpA0lfM8Cg0bEV3d5yN2BG7pyNZjKAQmQ4tMqwMVbLtw6JQgW0GdO7NiS2B5ZKNzh8vJq7ctaeY1REp3zS1C+i+tguujwi2dRB8HpUYX7FQAtB+7EFI2FW0DOYsPt16pcIsxjMq4dW9oRKSYNstnoHshe91tlWQTgNf0BH+ElpwDxxvKiBlDZ0JaFdWflDlu6xVVF1thWfibtuu/A==,iv:cSQIenM8MeFbx/HdXSddP1/ZlI8YAueEBEh2ypMDWos=,tag:8XhfPvfRmYxCqrL1kiJc1Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:vpvyPL/BMrfuBp/MZAY+3IS/eR+GlNU3Txpng2WxeO5rMrSuVhtfeVNSCHussJjPAWWjAfc9LqSISCKUFfgArIHtKO/F066Rca6B33Zcr5Ea2J8J6MIPV4CbWyungPCtLwR8YHlx3WJtS9CGb6KTm97WBJp4Al4j24Nlh6SdWif7DgEMeIYi0znhXXj8oInhHRHPPZmeWlo97LZ42rMUPah6FPvK6GUEydCi,iv:5dq0HZI06SAO/0NClGCDIgJqhf64zQ0aB/9Ve+HSnIM=,tag:3t/jtIcpXF0gnDylTHgNJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMEQxamhLT2V3WCtXR1Bh
            cTdzUFlxbXp0Yy9CaUtUN004OTNUU1MrMUFzCkpLNy9ORnZ6bzRIZ09oNUhFRDY3
            eTdSaUhSY1MxZXp1VWl2cjdWL25welEKLS0tIGF3ajd4aVZ1U25uN2JHei96bGUy
            amtLWTIwV3VCV2pPNjdyOU9MYzd3djAKPTaVFXyyYknmJrFIupPvZq0FjeNbvBI8
            YVx2IrZ11d7Hmj6ZgWHjCvcAtLwhxNFuq1mwWT9u0hzohgKrrmACOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T20:24:17Z"
    mac: ENC[AES256_GCM,data:pZVUd8XrPtv54bLZvSkqFmF5ewKzKGAYXFxCvCem7QBOYxJyhkj2lsoJCNYxEd4pQ4W/Q0lcjF1P6aRivvoODxspGcm+teqooCgNzRRW55ZvrHY1C0vxZlfYht3Id7ekJ/2LDKW+U+YHQrtghS/AkWTfDF8ztYaCW31TAfHEKHw=,iv:vvvMv/FR8X+Lsyw8hn/rZvNVymSGKw1wrHO0UwaUnxo=,tag:UUL8758v/Hg9Ky2RrizsdQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
