apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yOFPc2c+8FqseEBFL8VpLFBiDWd4ZLJxRWm3IxAVPqgQc3vhmXmftTtXWUPzsd2F6kTcK31Z7CKK9dw5lgyX1xCC8Dy5rHqpGFECnSTcwfrGMaSg3VWF4QoSroc8C7c2lRBZyLuWwtDh2wZXw/ULqyInLza0MI/1CNbE11D1Wl1JlbONg0B6G7gCXe5zI/EeLlKj/EdukjLTCZURSLsCdWRmTHpbhDtg8Eh8Tx9liC1y0Ctyg21bonhlNvqSeSbMPmETYUhb+JOrckm3iiEJGPysWUsa4qWe8bwII4YDWisyGQbhPtRSYcDoIIqpX1P4Oz7JaPu9lxMUWVN0iLQqusG0oinj2K49gqio3o1mvAKls2XN56VZKKgrnWabw+yD,iv:f9MiTKChBaBV6gjOdQ/79HUm5ljKKzUxD3QHe4IiAhM=,tag:0Q/U4j18cobkccTOwgF9/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:7yoQxZUaZIyCKPcyUUEdC/lw7l7MYPrNyX/ki6Lsp5EIWtOyNKu8MjrJ92dWIqzjpA2c1W1LvlMM6mdvJu6kV8mlHzEuoIjAoiIJhulN5HoCHpSZgdJ1nlzVOyNeFTfvtPxMcaai5fQ4krDmUzJ/nIjOd5U1i2YIDus5SiA0bH2dAfcljAnK7b8NG6m1bOGaFLfSOgyXOur4aNqcDzPVDEUKJR8p1ssYAorgH1S4DJ/Pljwwo7R207pC3rMA6yiLEFz5w7PkkZ3FimolWQ==,iv:0BROwM1SR38Di3B88vh2UjpCoRxKhFOK2DbE2+oQsw4=,tag:KiA7z9ARl9Nrm1cp/IGisA==,type:str]
    known_hosts: ENC[AES256_GCM,data:y4bMLh9CBhR7+OLp4x5UcocbCVJ4WaUhaDXq1YNP+ZdPyUWQ6UkYxKOrszbfKvHEwQLC+tyVI3CQWdPc0qEzU4z2hdiG3XhFzJSed3PxITya6m/JDb9mQ6S1E1mWNxuIEQtvKr3Ql/frAdqHgKaoJfAb3xALUpyGQ2lxP3eFUDeVstdmpuRxlqoR7nU1ft9ewmEJJVvo3YzHld6YGu1WC4UAmBo5RpAflQUh,iv:Ia4yQsA8cufUJGHRF/Gf/ir3gbKGn4nRBy2QJyboQ7E=,tag:NeB3qe+A+eSlCYC3s/7yDw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbEZxS0FNSHNValE2YkVo
            Q3NGT3R2Z2RmMm9JVEtsSEdONWt5d2thTEFNCkZNT3JXaU1KN0prdmNPNGU0d25i
            akYzcjlLT1F1MVd1UUtESnA0MnVTajQKLS0tIE4wWEd5RHJma3l5OWxRbVNEc0lU
            aVI2NXNuRmg4dEh5c0NSVFI1dnlyL3MKkmQC5juZuylJyfl4VNYAvRKki99XdUhO
            XJJX4YLLdVbC/etnPw8Vp3gBKFL89H62z50Z3WmdvZWVJZdgj++bLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T04:50:11Z"
    mac: ENC[AES256_GCM,data:cXW0gf/pu33iMlZs07IrPlmCes7N0KfewMOzHgcorYwLCM6W2Wqzad7+Y+qepABcyZ13X82w0N5LQGWt2RCW06QSn3j1S7+sI+lvRvnRjS3KRcWLOu3V0qSp2H3yxM9Bt6iEXdQNsLIA6kO/CCjAWr4iFSXILBmch6OsMF7Tioo=,iv:hyrm87Gz4kVMLHa7Sd6LHkZkETHYlFpHaoCS+xeHCsg=,tag:JLUXYdDZ9rqx4D4dNO/RIQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
