apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e/fFvZQVEr1ZI403CWmf+co8MypYJQBbrQLL1Me6KDEHPPRczi8+GAt3XlgTq75Bs6BDw/L4TudS9e2SFj0hCzWONsr0stsJAX5fZw1eaprIugLwBMHVaslx8SEaeRr5SBkQuV6z1swBOw2jC1rlwb+AgH7nHNvOIawig3ySQC2u/qdnwZKDUW1VAasGZU+MOnBXzObT9a8muLNZQHWj350VdRVOT+3bAzI1Cz5Ft0jOLx2ecEZ59ZQ2JEbZBS4hW34WYK1/Ieo44SNtOeNfv9rKkBYgOkHVWaQiD6KxyoHgMqE6BUfBmHZUejsgYL54lyT4d82n6cZb9egIgGo+k4bPhnZP2oGDDDt3MMUo4bIjvsD7Hbv6p8490WBPtYGc,iv:F3VqP83OjMKA4k9Jt2J9nJcL2/d/tiFYTUd7Qh358L8=,tag:318nYkeQZX8LlFpqAgnCig==,type:str]
    identity.pub: ENC[AES256_GCM,data:GDtWcvJx3hqoFIFrpij6zN24DjHTFaQO+fy/UmVFQDaupjaJxJqRjDxvtdimEScuvRjEzSN3qbFJWPHG2eBbNNVl/zAYH7bi7wQxuUL608LlUE5yAAQkCT2GRJlUA36Aib6bqkRQuIOKsxMk4eVvniSpwAO8OmWvcjDJQj6aDMQsGvOP9YbDstZOZm8VVGrl6CH0zmodbVNrnG6K6P6XgfoPbVRE1qDIof4N4/+A0U6GDCElB08DNyHKCwkPDNnnHAc5xZWZmuRQuIw+Ig==,iv:p0FKjyzSn7ZgeOFuxe/av6fDTJoL/aZVc65Sc2V96NA=,tag:Ui/vpvjG8Mj+xJ1yCpQqCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:joEA3jYWqocM59GC66OeE2psw+SVuVJSaHkQBN6PVIjMihnmXuX4+9wuaEP/P+sbnqjTnoVaj0zX3IkJAOX7TbwC7ghxgpPCyiB0ir/yhSzT/IPbGkZw5H7/KTJ6pTKJ/Vj7L4vzEJq6yTymiVCL1tHHFd6qyxQlvTCx7FxZ5nRvPonMP45xGp4TMtRtujyT7UEzI+JqJb6PiuBkZkEs2oHMuKB9xAaaQ2lw,iv:bHdxJVae8rJXyH3N1dpo+3YN4EnDVUfw23oekt1nMQk=,tag:qchl1fkkl0puYiQzFddq3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TE1FdFptYklNV3dnaW9H
            NUtMTnluVzNDazJ6SzVrbnpuT3phYmZnUHgwCmpjcHg4NnJ0TGhlWGJHclB0dEZL
            OWxzNGZpSHZvcGFNTFFaNG1XY25qV0EKLS0tIDh6RUhYWkNuM3J6ZDRaeWU2Z0Fo
            WjVZbytQb3MrbHB2M2JXM1JEendVKzAK8gQUqnskgIpnP8b5zrxNDkTHEKb/23Iz
            uPqW6lfH3xrAhJwlzk4L3fDwOfo5uZ+Ok6mpwMsMHpU64uTfb49/qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T07:26:28Z"
    mac: ENC[AES256_GCM,data:Dx5aZLSSlG/ppujI1Mgm15nBAEqimP6mCJRzigRm/YhnJJMSDjYNVFqjAoM8/O5OkRbmiedHf7+/eYuor3SZWJ2ZBRvcPSRy31b1Lc0SMiuq39J05PCe77miIdb/MoZnJmBTMdkDauZ6Hry2wZKtDvIS5dsWa+6n/W+UPnF/jao=,iv:Dd6afJvz/QVAtBuQlqKq0LGDs5dN2T/eea2go8HHLJM=,tag:jgtf3685LsJdkmbdrQb2CQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
