apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wNrOqA349z6VGX9yitv4jrjz5lOvyJXdxQ5vbGon+KHQ6ak1itIJmi6694SWkz0+FaMzT28hcKUZW7JLqXpKaN5At8EMH2GyzAL9dCDkwzWFAhaALkvBpuR0OBeWsbRJXkFsvBzkL8VwbYeQnMD+KVh0J0JTOgaGJsGSxHhpzt0JHqyxF46K/6/5BKBrv921lz8R3C2ROknQW4o4bEAiKF2S95pY4yeIZ39/fgNCrCloaqvZe0dQKsOUwr8oMpjKYB1QLbDzQHVzNjaWrxMOJeDkijBJf0db44+LEvNFeLLzC7DJJmypXvRUlH+Zb/oKmUgQgSGAYU3yE4miu5NPnQtZlSB5wqF7GRd2a1SUArRUCWAEVHjCEmviai9bHuBh,iv:Ou8PoiRGWJY3lVAzMoXOcnQ/mGxYRZnn2OlYOUnC0Ig=,tag:vbHNVFqq8FC0sCtZD78IfQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UVR6wIMcPyX8dzN2KngkLM4UoWf8YlEbg5mTi2Wvbwlki4GPTPECZodlDUa/6sSOLz9WWWsyVPT4cjd1TxcZgiOmPAyC58jhUf9zk0DRbmTQm7fwvOMoSF6IQmV0KLzgFTs9SC5MHYm16gIxvYIlYXfM1l8EWe3AYRBkManifllpRt0uuHsPO/LhIDHcw7YcnJD9SXrA97ksfzsJx6DYVElxbw47ETl+EQBDASbaVyT6uGR+CqkI+ugnx2zxcoU14QuZASToHk7MQIBlsw==,iv:D05RXeqPmdY1tDNcwVlR1yWaFMImx+np6ZkIbAI5cKw=,tag:SkRlUyaEzsyZKPyI1d+OEA==,type:str]
    known_hosts: ENC[AES256_GCM,data:OTjSc0TNjbWw+NRbB6kH7x6il8OBHxIsPDnjt4975SZb5wuBeVbEOIQgErp3Yvc8hdlRBq6D6BYiPvqOcAktPxLWZQQzvN5wSOSKyiJVu/sDjcC54p9HT5041fjitzXYzz91mk/FMA7N+aYp5RDEypVkzN6C4VIUZNQSPB6RgXO76kfDd0Zbd7ahJM+V7TL5B7yMO9N+MQdy8i2i0wvSIdkK6+68Y1o5cS/5,iv:m5QeNS+iojpVaB+sicU/0sqQj0XFZzB4TwMKbLuPYCo=,tag:hTJ/TFFllui1uUdiV3jMHg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bU5RWHQxUTJHZHNaN29O
            U1phOEJ0dlVFMWY5dnAxd2d3VjZpbHlKb2g4CnJ1UnNQOFNBeDVGeW1DOEZWMGk1
            MzBUQk5LZVhzQWlxQ0ljRU5yT0haVTQKLS0tIHlqa2N2SnBhelJJZjVXWUlSUmw2
            TlZrK1F0UkFKbXhCNHNpdk03T0E3aUEKI9pDPsqlmum59UQm77p8QTUBzONgYX2y
            p08J3hDaXN8g6zl7OFhyoj6jmgTX/luZhCvRO6xPtmM/0RxIPSPnCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T17:15:38Z"
    mac: ENC[AES256_GCM,data:WgQBQ7riKHBT3PeDOk95rOFa6j6u3vC19fsflejyZnO21Lq95I8v3Gr3nhY7McfhRebmBFwHbKbxqdjDGuJuIAxdnFjux3ZEuG02ZNhmB5uo220GQcah8oGuegEu+0vVP1F2mIhG0ElBe0JCICvZ+C4MR+SdKlPAdQWcZqBQdX8=,iv:76YQkkIXQYba0lkrT2hwyl4mY6Y+2VYwH+XZtvPIrmM=,tag:yWK4SSL2QYfZ0UibioRBUA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
