apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IwPfHrlHU/GLYbFdh2N0df8ULV1AZGTqgMIR1mzobegTDuePG3pi8rqFKU+rcLH+HElqDcdL0W+Dv3bPDTw7mb53lDGlGfveJVVd607k8nxuOLb58L5XYEav8LLnC32nHiyaR2VOFsdaiOW/VuTlKlK5FVRed+OT3vQAGNoxZ8UUCu3i1j6Xx2ocuO3oTMXEvUNx8ZZdHTsc/YGHTgql5/YMC9AjgwDb8OniWdQUGUCCxIxH2INWFk1zKntWAGmS8LR6ASCrDRhn67vDHqGNzsGX7TLA7fssJOakZlbMGKiUDSgIQ5KiRniMrOVCdbd5lP4p94ynmS84qiPeX8b4XQKfkL3Ed9BXa2V10JNX9R6yoMYWp2zamiKWLMpr+aP0,iv:RW+hTuqPogM+/8gGHpT8zLccoteYOR/bFHl3ZGCwdNE=,tag:p+06FQvVJbYUFxiXEQe6WQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xGjvjwXj12wkZFsoJ4UWgR0Awn7eC73IRM8q6mq+ThE/9GbECvP7hPxcAp65rap7puooEGjbLsApMleYa3dk2mQd72zf56Wo+q7fqdeLYcQQb69bkFqA4mk52dG/41oZbScqegkbksJ2DDea5m0X8nZRWtNCyvGlzTfGk8J9VkKb96Jh6P0654GPB5fFvmO0uiS55nOyrrvY10TaGVUesljQ0qq1QZniIyt9fPJ8BDLRzbWPffGsxbZ2OmnDdJRM9b4lnQJIiszm6EmfHg==,iv:ePWVYNJL6LrmcuhfCvW2GQ3lhEgTLh9Li4DdBofgp08=,tag:E/KrHUJO4fSLoQow1hhfxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZuxIt9W2MNobweyQ6Cp+ObCu0V7Mm/U4Yum+vD9WJwC1ODjE9Vwwgv1VtQ2xPJrGIaaSePmzlAo/Ggc38uIoEU1pdGiXfpiLqIHIt2VXnbz4xzwCeWz4ePCzoOXRUyO15cJTHsMYL3fJGepK6hyi0ah9bH3DqIf0AMgu9BQ5pZZ9+bguid/K9BOchpZEqB3Nh5P1zNJU1sgNJ7GtPEIO5DJzayTY0DuG0Ayh,iv:i1k5YMqsjcPvIXtH4yeqJPiAG+uep/4yDyu4AvnydVI=,tag:gSHUmQuxEqZtC8OpIcuItg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ2ZIVHMwbmZObXNzMXAr
            OXBYRWRmUFgrWWlWVkJQYWQ4YWVzdytsQTAwCldlMTUySlFlallPOW9tZGp5QXVT
            bkRxTHFtRXZZSmFmYTFWQXdVRFBka2cKLS0tIHdQZENGVi9LK3pVTjhPUmRkZTkz
            Y1ZHdGNNeGE0ZGJjbFVOTm1WbmlSVkUKjRgAS2OCa0MQidKOPMhuFc/C9/lfuzTf
            OrGD00405imxkMJBPoB8IrF8Dtw36S/OQi8fm3HTiabKHVEpo//0pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T17:50:54Z"
    mac: ENC[AES256_GCM,data:ziExL/7c1aEd2GYl9+UGL9cyhBiYR8RdlJoiCnkhaaYKi04jxV15mwb4AT0BnjdKaBFkbMbVTRE599zehUYvS1wCiylkJtIq1pPEyfnRB2bruadhHnNuFaQpuzHCfee4TOk8i55NhjIU9+tXovJvrnOxw7HfOoX9gmbrySWCUT4=,iv:YH1g+7DnTBCosJr9ftrsRJeYCzdDKAq0xJujRrnRqWQ=,tag:bRBTFRyMoH3l2rUhsK+JEQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
