apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:61YkqCvAL7e0SJgiGwLuMJuhmQL2r21zwq+uwXg/YBmduLJjGcZ34wEGMKLk3oClUBqOmrt+2pgxIG096ICHV2+aduucUoHjBmG1evQtosSZYIV1KgJQPWDGQWt/AD5AYQNDos4nb7mEVTIfir/BxJZAmzjIZJ9Be5YbV96hDk5HbpdaY+cfYhFKDJnITzWa+Kh31DO66AuZB+YBHZsR1k53WuJsGaYZ62iBx3a6dIFYxpS2emfXOxNJ6WgUupcgq/mtA43AQpuQc/TA3LNjQttVLt/G08cq7G2bXKiAek7SC2epNNB9iFilVF2cdfs+V7Wm8xt9s5YJMNk68w/j2s+RkkzC8WwHNgSjCHEWTLEg0oAtFcDEDUx0HG9Em6DN,iv:blr1tTg+KKq487AtkTcpb/gD/fRv13h63He4DJYXGbw=,tag:cq5gP3bEySBg7QZqJ/jZKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:BjGojboNmEC3HHaI2nJ5aZOiw9pWzMpiCY89vHv1VPIjOunhkN73oBJcaA9h4kn6dlnS84s4C2qkIqfAQIRFfNVypdWvuiKHz9RXjCb81BOxILTDzdWgtTY398fboWsvBxQo7tFHrpDqGFh10b7uMApCokJgo2vpaB9ApJUTEpXzxTFq7JpDCvDzznn8nf63rGWkFenXxgx6DW4apBAAigvEIZwBWM5a5+Pe9HASrXoN6O1ajg2xBN20ANA3gZ0WVZyHqKOX2HT/Oms9+A==,iv:QhFXJLA24iVatxi6li+4hPGTbBXbqVcAK/66Mgkqgyo=,tag:bGwPt0b2hXE99QiOZP0pXg==,type:str]
    known_hosts: ENC[AES256_GCM,data:e77NaV/J8H9Jx3OpQt4qwWFasvR3kvpozQFFFLlmgl+ezy2jF0x5ptidjvP+3OIjn8o4N4TB2Exs3iwitLYEEcS2rxmbetrVkMhHVwrzE2XctqRAEGbUAoj5czL0QSmbPdtep2ofEOgmE1wwnbqnlvt+ryOgWflSZ09KQVkPK1TGZPqci9hhAefnH5wKmkInlWdh6NsscWqYQ3v4aGPkg29DxbP7mYt6mb0c,iv:QmPRztoGjI5M/ysxsI37rftGRGFgkI4fPoawKFa16lo=,tag:bzZF377OYA8lPKlInHeXEw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dldidHZHZEJvcTd0SWpQ
            RTJPbllCUjNMMFBwZkx1dmRQMHhMcXgzUlRFCnljMGxvYXlrWUh0aEdHTE1lR2l5
            ZlBWS256OXhaRGN5UnM1UXBYb1dFM2MKLS0tIEd5N1lMemJnTG9TeXBVc3k5THBO
            QW5SUnF5TFh6eTdTODZyOHRQQUZZNUkK70Y0Rco/Sc2eANlhjRhoisAx9TwYMW2d
            FUai7dD+uCzyXUWNU/egXVLPXkthsT5cErNZt7CEpWAuwpc0IB/HSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T20:38:30Z"
    mac: ENC[AES256_GCM,data:qrMN5UD68Xq66rg7emzl3k5FnV7E4tbxHVnQZE4ijiBIqyW8VqzfwRT9F1tCCiWQslL6Ci9M4hB23SVD5kBKD9cyNssdH18Nf0zn/O0m7bgluAJ19LnekZJH0Vlm8RiztPIfXCsQHIWy5zCskRseg/2Yueew8jw6uG1ROyi7PK4=,iv:QsKLmxGC/58p97devCPOD81nizcOWmh0MM7viDssWaQ=,tag:yEupU/G39M5Xpfvoz6houQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
