apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RKlOz6yTHd5reFxccdEeUwknNBbW30LBU95iYn0l6ECG4QQZmwRfN8jctaJAPcX2A5iVxV9sLdsm8r0AmJ7L0/fTwg+5ODgjCQA0xEzSFZq4+lj9ANWbKxtxceToDQJdqoJZ4v7pUrK5YiGs4reAiozmRQIid5jXJSZ9zj2efjtxITLaDiFWzQkfH47T02valACxQcHBNYom0tAQYka9RK8ofPc0/T2FjcPjssJw0/fMEKP4K8qdfq8CGMcyO/3JJYsXRKPF1EbW9f5S682c8DYikqfaz2t/LOPUTJHDnuoqV5T8+sBPBbUd89hiN+U14o2uaspgXONp1Kv3+7Sz7YWjnr2Kuyy1AX46XqicRRZtoRaLIiK9ePHMuZxeu9Cl,iv:tPdCKmfB/41ACLeRJT+biTpRxTVioEARAtlLWBYVf0U=,tag:F9E9/ctROVTBqGm1n3k/zA==,type:str]
    identity.pub: ENC[AES256_GCM,data:swGUT4ScSqa00NIwcAl7nYlC+vj0/4U/2g3MZURhfRfXJ2AEDJzpkXNnlzaAV+gv8qmQzu/li+/lIuOQPaZHbEbNK0tdQi2Mtjb7pG5A0QjzzgLddUHTHRyTijMDspnWwLhQH8nk+qVXPm5vsUmze5TpPN2sUIANx4hEkEhN+S27F8moN+IUseSGZtZ+e9GLjkkHFKgbLtH0Iwx+dPiZkkWXSxgrdAj2HTZHnM+Nn4hrI8VPvOIcsMeMHoHSF+JCpn4a7ZAwOOstssQCOg==,iv:+INPLcznlKqhZYTc2aDbS1r/v5C1yZHD0mq8c4D2ZRk=,tag:Na1pScFcdqzx8czddlxbAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+8N4e0yuGxxrtPcnkZCm5WshHR4j0quF4ulDycztyiUjBIRSLKzEqfbr80z/zlRvXw2U+q3w3ii2CbCtCm4Ho9jTqmx4dn9uEiFvl7ZKf5OTsZH8PRfoajnQqt0cD8ZWbJHqocOaKm7T1AoMpqReNJisOTH2XuLg5M3sdhwEOR5aH37lA0VLqE7vhrpPgC+M2faveiModq0tUvRw/L5bOJH9a34w3d0gijg3,iv:wdjcMFQreT9cm/IPwMaTbLdQHSKfU2Ma9s2lM1aT6uo=,tag:ILWI3YRd+jKnWhM9CIO6PQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb01Fb2ZLcWk2OXBLOU5t
            SWZKTklOQ1dvWGl5Z0VqOFZmOXQ4TmdCcXhZClRXTjF0bDA3eGdIK0s5LytzTWps
            L3V3ekNQbFJsSDMyQ0w4Umw2SkNqR28KLS0tIHc5SEI2cUFENXRDS0dmQ24xME1M
            NUxxS3p6WWdlSVVFaEtCWHB1Ti8wQTAKemTN46m4H+v+XLJBQyj+k1DxfKpLlgMc
            6k0l5iWwKly1GMTEENa6JdFcQXBg6M8TxslQmWF+SlNKL4qrpTV6XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T02:54:41Z"
    mac: ENC[AES256_GCM,data:kFuA2gsNhpGRM+SQvtWy9vrYkrvM3fqsmC0PQjvGwvN74Jw89adJ4GEOmCaIi3HvsfWtd7+Vqk0Ovi6Kb+/JDmvfxW0ptVeAbFSWvoOENLBCg66kD9DuWfY0/Y9QYqnE7WlYbxiFyxl5QDXMOTsMIbWTPGRaB7VEicMQt3Ku5gw=,iv:NwNurkPL1vcWPKWRQbOsVZqLDFAE2+jzm0Gw2SH5+DY=,tag:70gmfALjihRg5En1M8O/AQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
