apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:g8y4HebrKGf5LR3cm362cBMoe6Dti2WE5uV+p3Bgw7PaarZ1QMhAz5yrVtVm75wIpvoZyBpxnYrBvB4jPZDifT9sxxF/1wE77pFbnNMXvA1u1705Yxv+lBeF9zDKbSb9t5pdSaAIPeBWx6ENfGZxsKHMSgnrjJ++30vfEeu3u3r9owd8RMIZR0QWkJTEas1hkwgueK2XuIdZnnY9ujdkqwJm1Dv3KFpwFlN1yfage/bXPhoEZwOLzm28NepEaqyoS0B5kotRD0PZ+9u1iHNBku6lhaXBwV5V4PzT29XNlrSyu3KkC1HiaIHbo41IYaAI9SEbnjo0IggLqtlEWPKnvj6HvdDyRqiivAxhB1gEBLGRk6RvT0pM5xzGGUppzuwC,iv:g7HTlbbBM7uJ5HGwGlBRbmYBCKSyVFXio4pXv1VZ1nE=,tag:83sWB4bDHiAHnLgWT9j6tQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:NyhTv2o5XDf8JwBKdoqIiNgTAbh+0AMNmPJQ520rP9JohYwSNfwBA3O5r6bcSKoJDFIkPKVaxx1vqiNEK5qrnKz/x1Ty+EyoDZJLR4XiiWYn8lLJFNWUahmpnCrqBkWOjdm/kh1b8FxfYu0tIzDOutMV72paAWHmgumqo1DqDCHqcapoExUNQQUhGcDNHrBhgpCcR5Pub0PfGlpnYqM1rBPiDFtCTxOsndQD6cvAoQGyrN5z+lEqUxtt/AM7eMRREUEm1yY7KnhBOaS/Qg==,iv:iAKQiwB3mYFfNGcd/zNQZU8AOa6z4p29+HvvRNpitT4=,tag:CpVnnErKdAwGucXoE6S6mg==,type:str]
    known_hosts: ENC[AES256_GCM,data:xuI+3I9Uv18yzdBhByw1rQ9npvQ4S0lnkQxqxXyvRldMyF6nexJKjq4P7Yo/nsWLgH0H242NyLqnackx8f3rBhO6yhdKwItSpYem3SP9O/cVxSIBUsmJPv+v0geZavjTI6KCkK3wVSgRLH9T9p/4oLq/hN2ue4kT6f2Jk7GiFLNlyBTh/4ERAPRd+F2H38IFVfkD74FfOTyC48Ams+7JyPlvDWtCpjs2JmMO,iv:55EmkhFlBhtHE2akrMTQ4Zw8KkXxIr0OmipQDEWT2mw=,tag:qgdWDdDKBkV0uVwVV6myLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eGFLQ0JEaHloVkp3cEht
            Wkk3UlZmOUlUUTlES1NHN2MzUDhadDFBV3pzCkdid0ptMXZDcFNUSXZJVUc3SWJY
            VUR6WnRaYUl6MWZ2b2ladHZhYjFiNEEKLS0tIGR1ZGUxQVRHZGc5R1p2MlN4V012
            Y2R6VE93a0NjYjJzTHdQZUNVeVM0ZGMKbAvPydag8Tix3BBzDmk1ot/Ab6YGj22H
            i9Yob3HP/zCOuFRDb2vFAkOzxBbj2MPg8Bwc+Hl4fzoXc+386EtAFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:30:22Z"
    mac: ENC[AES256_GCM,data:X1QSE2Cri1SbIGHjBT0USATUp/KsLKQ9zUF1FPcXUEidQptXcY2dOn+upVVDBB8ecnauROda6niVTo/ERt4pKv9UPXHpwfSgTFABUEF01UcihoeZM0qQfjd66Kiaefvxc/UYg2D2fqAjeccxkJ4bGV/v5nsHY18e9YIZgZaRdHk=,iv:UbAk1wH4WxF4v/zvUsq0+YmVByXtQAZLB+0laDp3EA4=,tag:UFvmF7knGUOcF+sNlgETXA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
