apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+UZmIWwlFj+eyTsHN+4+Wcq3MbkhXlHHvRuwf3GHwsi5ZJCDl+QIhJmex4b/5X7IH8SM7CVuN+mwVB/ZAIbCnh9gnubJNYrp1TLAjOhcmdEcIAv1X5vcZuV6MDUjlhxJ55h+zf/1U5laAx+8r+KJSrQXfWJylOwAN0UisYFyGFOuGEbMGNYsnHLnRPGBLfHNrCxt/1qQK8batR6ckrMDD0FStVMt78wi5KRGcxLVONzWiLjTzY6MWGtSmURAltFb2AcrLufnz86TiAtwPhWYpfqsfM6+WxBsTA+Iw0B41IYs8FuSEh70a++mVN1V5ZZApVscD9Ow33yHi6VgIlPvH7fE8J9sShH6UTc+1CO/e1WeqjVf81bdq4OtBpf+4DS3,iv:1rYZdWoVrhn78WXCWaLWGWPf3T7jri6UyjqVkjGySqs=,tag:e2AswdqjDdIL1Vwp9TYo4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:NsKGkOF2Fn6mSnpqsr9WZslcXwcqLBio8avorsbyN71/f7IpiTJoblFmJE6j6O1sfYlpT45bvyHOr+nhDbr/72rfzMNsT4pEuLDsbESxt1ovAQc2fl5eVojaH+WRWdmqOZzjcxvmnFq3BARzzjOF0kQwIaeSLA52YXXIT22dZEBvRRPCtCrcAmfjsDBzeEEeN/C8B9udp1yyZpI8R0yKZcmIlF71dJ2QYfZi6V4lD8Zbw4DjDa1yUhEum1Dwim7qAlBacH18EgJrU70sPA==,iv:zSzdo4cIvT/PLhy/9bK13h9Kr8bRbP1nA59a1AVJSss=,tag:n9Q+9fsXMKlZEwm94x11jA==,type:str]
    known_hosts: ENC[AES256_GCM,data:HAZWkq+CobAeD/exL9FcgNkCWpWf5a3fde3L/I3KN3ZHHPevsopuDY8Ys1IVNqz/pwYkOys3snRJD3Nqr1AvMmntmpSv1VQ5QOMm6vdqZmqN2/DCr5LzOP2DVBrHp5U4iRHyzIHz254RiCiY3IRmoiOXijYLZL9wPn+gTVEyrdCKxYQPwvBg/KA7CZXEKx0GKzZDBuf/AzmfKTtQtsJaUF0YFdr8nbJIyyO+,iv:MuHxM6VUfhl47eGVxIP0S4/Q8B/H8E3e6xN9zbxG1Pk=,tag:hXTzkD+GY4fSAerP209Msw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVDd5d1U0aUFidTFHYlZS
            RElDU0ZlNldUMUR5UWNDdEd5bUI5L0JUZDNrCnBtbitIdVAxODF2TXQzekVvZEJ5
            SklkWGFMZDdzZFJxY3Nsb0YxTmxtMWMKLS0tIGhTMEJqL3FSV0xYN05tVlRqVkRS
            YUhLTE9Gc0ZOUmRkMVFTd0pvVXhkQjQKV+KaOjvK2RyFW2O+M9nhYyjopkfXIDfR
            ALUWzzlewo+263RcNtK1WaN1c2fGXQCL4hmXuOGsYGyUdaZeBh2udg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:46:16Z"
    mac: ENC[AES256_GCM,data:69Eqlye+MW4RF5JtwNq2Pa28YrFViQEQvtgvXwYuFIlhJ2E8v8lHVv1Z7SdMJwM8Erm6BZ7VX45PhHAdfxfUHaJ8nncuaxr6FOP60JLvXBITiIcsfYKqxNz4P8W8gMtDLzZqGDy7hRHgFyZkZtu8yRAkV6KLtBsvD8QkxhNOT2I=,iv:9HOCZBAdPZDR7U06Y/VnB1fUfrtGh8e8K37xqzIcY3Y=,tag:VN6EN2uJkW/CKkFzX1EQvA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
