apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Sn1VvFY7mLQWDnFYJfBKBlWrkmvpqJVTiTPsR7zDyNAN189uxhotbnBe2zyx1GJCT4k6iT+fOTSRV5aPZlXLl2t0q46fy2xhFGIeaDIMEXrofrcWz/rg1uiX/fiMvNQjRFjRhoY56cAs9fzwcC3J28AkCVGXX2saUK7B5C3nA8dCfLcKIgqFKqtjypNOLckDJ1Yqp8Q/zb5sAIhotmO+M9mzgGGM3oy01uPcn/ylnwIWmwqsSsGi4yQxirPeBKjYsjlO8rjCCcG6jbPzcqen2yiUJuDAWSSlt6119CGTnQuTruh08KizvxE4E1zMBo5dYqo9CP28zIBfxLHh2AUq6/iveK5kaGhrGTAC6kB/yb7R93FPc/KlYcffEei92t6R,iv:HnkiDfyBhFT77x6ULcHDrTPC8TeCHh5cFTPHwFlfXPQ=,tag:VIUMBG5XA/ge0I45sawK5Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:aa6gN7C2qjo5DvDu+qSN2XdplsYOgWJnuBO9sEeUbCHSH6rbNKBKAqKZF2jebygvhiyPCQ/pLz3K6CH6P2MVCCEVwTZz6IckYAQPoM8CGCmLdu7Uea4Jgpn1uVyBPmFSWtO5yXkl2XIsuA+SlngcD+aUgG4JnX1rTywRNDB4RxPPx69k66zAs1Scmlk5yNP7JmgiSxLVlrkDoZqF/o+s2R6yxrlww9mceQYXpitMNzwe8mGgWwC1gvg2S1ws859HGms20KJBPjDkzPSYFg==,iv:mMN+OBoSt3323Sjrvv5d0pL8dS+l52hb+KRVmd5xfK8=,tag:KRmlaM+2h/wEH9+KKUOBGQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Jt8F1rAz7pfEqiNukQpPiFfkqp/lsIXlMhIEoWXP+x0ayYDBEE4gxLvPvg1WSS4NXbR0UXu3cR+d9ZGYABIydaVkDRLk2nM3+wAGd2bm8b1TyXkJYvYERMttUdDD41omQhKQ9G0rkwhVs9dwtBOMW8cwHGjEZhzt7EB/fvIKyIre8VEl24bdWU2pMcZ68agqXnpTjaD6OdFrxjXJbZ7L0uUMpCAl34x1/OI9,iv:hI1fnWGPLNjdqmDBn1TbZ6dYEsPTJIg/ooxsAY8oPlE=,tag:19RUkljPttmQldxXWdZdzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNEpjWldHaUt0UmtyS2R3
            ZVFsNHVSUmZObkdYd0svd1R1VHUxcmdodEZJCkhkV0o4dDViVldoSUJIUEhsemNM
            c282cE9MQ2d2YjZqT0pKYmhNcHRnaU0KLS0tIGhJcGxrQkdMemdQRm1kYXNidDJD
            OG53dmZVTXpnZ3VLSGtBYS9jMExqSHMKT0YUCQg+UwYa+VMmFd+fN6Qi+Oq5y05j
            oo3y4SCwyMMyh4+47/3K88iVQVYWQd8L+LoazN3aJYr0eZYpU+uRsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T23:05:27Z"
    mac: ENC[AES256_GCM,data:IdMG/Nc5Ud+sIEun2/Pj2wEFaxQHiYXXxUGGoyFB8nVffgNaaeXMQQhMTyEO/8NyFCjDMujda3dIY0tejo5cHABLPjaR/F3J9ED8QKmlqw6AeTBPX9e9y/cfmMyXR3hsorv6EpAafurzDLwnuetNFu8MjEPy+HTCKJompUSpbgk=,iv:dXIOMDRlSp5Oiw2puhKJmhyFFyygLacNbjG9ODDTytc=,tag:n/XCrZIBTvLL5Rmwe3i+Tw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
