apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:S9npvNHNLeFlJsf8xH12Wmq9vnC1HD5gqgma+YpR749zirhb/oO4QgS46wQWHr3Peh/bCpxVhSdu1v1QenAZqZKQEeCeMBxvuuFme6Qe9LapvjFAY3pbgYhDcqCpt/3JJymXnCwhVm9hKdCRlKpbfM48edUyma8b5hyJlbE7UYG3dlgqUZQmfMXgv2U/vMQofysC1B3Bcv6B+96ZY+cuCq92W4n8xUgd1DcyuZ1VK82uvUusf1CaLwK9PCp3JkfisaP7oLks657qUy4wHYRwkOqzigNK/0FH3PVhgLNRfqlHeNYG8Pd/N/0/D9v5TIXmeYwNiXkPMRqgZFsm74z/Ki3wEklPDjSc7paqGbpY2/6nP24KIa5+BdQJh3VtUnK0,iv:2cN1L81SQEBW281cNc+1XAR3vuCAhqNa9iZCbeJMEIU=,tag:N8a3KoLThrY0LNWeqs/B4A==,type:str]
    identity.pub: ENC[AES256_GCM,data:VL2jWkE3Bc21yO1GVp+KR9OfvB4LDf/OBEuJKZaXD4+KY5LeP+BMHuk6BoqMkbXUIJPKRiaXPSOnJpQ3OTKuGGvAor3iM8CTn8xh8Nk7EgrT0CXbZnTS6I2bHRdR8E+s5LaKnr4DVwVwVQJNBU69OlR3FAbyGmQeV9ybNQlSKy6qujxpGdVVbHwwU/e8vmgF5pv2PuUpZ+WbAZUkpG9xktq85MyzjFkZIDtZGrh4y2F7Xd+AfsJcjyOLa0+ehHrfCYUB9lwsjvZcjDT3MA==,iv:FokodVd2qPRmukFqh38l654DMwaquBaCrZ69sACmvic=,tag:EcUY0YY+TuPDvBV6E8rHsg==,type:str]
    known_hosts: ENC[AES256_GCM,data:P9bk8pSKdS27NiXYFUwIOOQJMdZqBLFG4cXm7OKLz8Sg749Hrqjgqo9FOPrP5PD2wKWTPLVrTp0QPEuOZDHp4ipZVJh9302JTH/YbJy9dB0SO9E49TNzEhjUrieeXJg4Aira+iu6qER6QEEHuLZAV0AhnVI2wqsK1cpj9qosLffHp1SadSRznol4xLcRa8tU8jIi2BfgqL3G/3zet2/XAPmN4ESPuERK/XH3,iv:fLcayPu5md7UACWRbeLSLuxte3aqJgDktZK0ONPzQcA=,tag:DbeVuSxoE6dD4a/A2qe1uA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRGl0T0NiYlpwcUxUSHUy
            bFp4Y29mdDNEc0JuY1R0dU5SdVhQTzRSejNVCmgyd0liNVhrRGNDRlR2SElVM2h2
            OTFoRVptekNaTXE2M1lWOFlzdmdGYTgKLS0tIE45endqRmtvbUdqRnZvakZhcE9Z
            UWtUaDFZQ1JvREd3SnRJK3JEMVZEYk0KGQBTz/pDLT7iW/3R4xFzbtjY/CEJUeaH
            J3T6GMN5zC9dI+NAbDVInxxS6Ij8/tz6ahmP1qXKQ6E0mNCb2uA+0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T03:45:18Z"
    mac: ENC[AES256_GCM,data:J3aQYkPo408CIpSmdz8Yw1z7u7dbuCvjq8AsdfPU9wPeup4SgA3ko9iJZjs8rCrHWuTzEPnJQr+gT3COowk0fwNNX/COhsw3A547Imw1i43cb5knbFtxqbpSbQgb4L8jL+916N7mx1fFvMSpOc0goAFRkZP5VhXAksudhhKlJ5U=,iv:rcYDI1nrxac1S4YT9g/XADKu0x07p3z0zDEs74C9b5I=,tag:8h+xBhAYY7WQAgoZb/IBqw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
