apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BOlKPmiJwZuTMw9WRcEzd9IeWXpDjEHAWDluhobLxBP54tlmBCtV9QRStz9a6WUhBM8ufM1vTys4QeN4QTAv9RXAsAve3lvyKspG12nVuZTpy7iz+vFxk2i/Yfh2i4tVQlgWGZkmw3/7QimewJFsVxFnuZwMTpQjDq2YzQBQBfe2bCUgcrTJkF6EHlTixmJbOau2UOiwv6dWkWWxxemmcgUF3oQNEk7NrHbyS9RKMtcc3Ad0JK1ebonoYOVExiI1mUVgPU7OrIk4if/DQhId2o+8HntQRG38Xkh3iqeiQ4jSEVjEv0CxWKfPBCzS4EEKNvJB+rXJDYueajkIz5Z5TJip3m95rZU0GvojyO8l/zKucZUInJ63l/yBmiX4D8wY,iv:y+uuL5h10YYA1MaTI8r7nTZ5Wdpp6Lmytlu+a7WDJRY=,tag:XxfZvP1vgRl5Tqt0bZyQUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:KGfGbkPIBzMUVieMkYibMtuCzNsCWp2L/LryXLU4Fq6ejCi0SaZZSXUAjOvY6WMF96E/E8+RWCe7I068t2TDTDIyP3V9icOx0fW0loJYTUxEk5yCMT7OFMYnCIIiulEJ5dJj3n46CzDy/CKBG+RbqSfFlZysCD0G+B3fdG2fhZgaLoz60EgjBtL9Md1Hf+4E6CmB5ozmqHIowswTduyexQuENrsa7qXOPHd6MdMrj4OwT7thcTCo3wRbgwkE7pNZoer5tYg2v3jPARvgNw==,iv:smtU3fzDVeCNjA7Rq4hYcTSnYwXDDYuhkdRa/CM9bBI=,tag:QqDZdeAb2nXpMThHqd0jhw==,type:str]
    known_hosts: ENC[AES256_GCM,data:RynaYljPWt5OoOFPg7thMEM5FR+jmn4BWmOcJ88+OKmSwwW0DMOXCT4kMtMNOJNywCkn+lvmel/A/Q1p1xYhEr4DK00yuxYROws/KvEijYuTLidftBc1NGWqnUN7HFHs0UMEPl/UUIaU27Fe77AMDQNkAY5ywY1iEyVy3HNkLCk4nM4crkqEGIv350KLcFQZcLv+QbWpq31ksZU7Uv4txM4vyNXrqjOyxoxS,iv:KgyMOmFyvd8sOIGucL6xEt1kRYRiXyCBFDJqExOA2kM=,tag:A1SSy0iOqI1ciUIEcy7/5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOFV3YytsVFF4N1BGWnUr
            TTNLUHlJaEZ6eVoxRFpWaE0xWHh2NGVIa1ZJCnAwa0UwdWxKWUdnSDFQOGxqQllw
            anc0MjV6QUJJWUxWMmFnQWExNklTYTAKLS0tIHM4VHRvM0pCeHZXWk9IcU9xbVVu
            bWxpZGRBZVFGbEhZWDJqeDJpWk1Ea28KGinKN1jPjRO4zGq9cjUVepwNU7Kvn9w5
            0g8e7G/24yRr6jqNIEGnMn+qUaQTulnhNxzJAL8i77Kxu/1wq0R2YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T22:43:26Z"
    mac: ENC[AES256_GCM,data:n8Y1SUwjZ70Set0qdXLnlPoz/udzzt/AIwYF5VUumkogTAVBMiMQLRpUpcohStP1iKRUSUYb0bBUSwKkZDscik28eYmBMfQ6PoMWvW6hVJdSHkrnhPhv+H5/JP2UboHkvq1ijAwbRQ+4DAs33v5Uvkn0xRLidIBt41KtCNLUuLE=,iv:Rd8jxNVTb9H2RGJEqGGAduaUaksTrCrZJ+7aEGS9Ocw=,tag:b0TnnMLKGP7kqzUgpFJuHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
