apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+FlgYvjcasY8UwlkAo0bv0XAkIFQCm85IznG/phDOcdX2xDeY/VIPAv8uxi6G6xhafu4Gyf81zX5RZ3IrcY8zHTum0gd9G1v/lgbIvBmMnMyniv59nU2Eyz/RECe2ZCbD5yD3q8LNaCaWyv7wOk9QyQ0UwQ+WI6IvyjWKiDv6TIhqMlMBDB3XvuwjNvjKw/8ZQkPClUuOQPpn+vfrcNX9MnIj5L0nuOmSS3hqO7ZtUGbu/MzK8D+a3slazENDkVtgRtIFXf/N2r6pOhT/zehoZLw7NVdLurlMljrxwFVibXX6ouOBQX8uTygVsWG4eFcRvkgcQa5qXVpauimPXGfOXZnt1/uf90HvQnzIKnl1Pt41w4fYQqPBw4QGICQfCdA,iv:J5gKlVcbehOkyqEHGRpgENitBzeiETB3MsK9eKhMmm0=,tag:KAlOy2Fo9v1V+a/qamfxtQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:svGCGb2yaWsd3+9zwHxXJoJgs05bVeV35q5V8ijPWg+ZGWOvyNW9gkYQUgJy8DiV8FtE4hfTexn/NhhRX54acb4Vi+dIuloDw7P6h2bL/pFFlRAYT0CyVi2p2amV9NhI/thZ58oyZ5Idkk5NMykakxkDRS8v6NKwTS8W9QqQ2qWoh5lK/g0CUW0yGF8eHPOAcIO2SznCqHxuahaXiwaQtrMzdL4eAMDk9auKshDLc5XkLoaPf1vrnTXhHnYibKRCT9rbF6fE0TBTlNHcfg==,iv:NVnz/x++9haYzk+4HFSJG1a234kMdUSv/YdQroC2Q08=,tag:lyq7AHBPn0cSJTEuqtMX/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:5vPDeiQ0MlCsmV9ZOWDoSKA+f3daYa1J1MkWIUZ+uISp0zrbpD6P4Pq4tmE9QuOEKkM2d8LbQIowoBosbZrPz76Vr5FTWCuTbsZoGBdkBc0ok0fq++7cnnhmEWU2OlFUvgbEeTEP/0Q0CMNwmk9P/8PgnsUqM1mdmkpPtTxnEeCdPsfmCeZLekaG8ZYtqZM13VgYzG0TLTxeBYKpkVGvBjPfPSf1hy4AEOl9,iv:M5adHUuIDK2cmio1RL18VRgTAlks0g1Yo3ja1XzQ5KM=,tag:C97UXTvlCZ5sJShVXrw8FQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTjN3YTVLL0sxaTdQV25X
            Nnl2aDI2cGRXdUEwcVQzU2g2TDJ4QjhjVjFRCklGbXZySEIzVjd2Si9JSFVEQ3lj
            RDF0WnArQmNtK0tneGpTdnRUWTVoUVkKLS0tIG05QnlxVlZLcVhmQTk1bG9LZ3pH
            dVZZVlRQdStOb0RmZlU0WGpMOE1pODQKASo3pHVaXZsMuFtC+snVctVrIq7xRDca
            +8EQsPEcQKHIpwOl1PSW86V8Q+7C7YaqJSgf9LoWe+aOgxPJ4VBGfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T02:08:28Z"
    mac: ENC[AES256_GCM,data:tezka/ZNLRUD0eEFF+rRrCMg24Cp0afU2yfxB/E54VYA39jUWmtTJ1xghsIe9X+h2NfjMKMwGzmBxSINliKOjEpGxkAQ+Nxd2aHgoEJNfb9aAqK+HeNuxVzF8dNiOAPNOvBfSQoyDuTR+/UNrIkpVtCWXIPotcIgfEORw3BW0ng=,iv:Lf46CfFqqELSmarRHgTrCyvDFUL4v0XfF52P38+MlS4=,tag:v2I44b7jfhrbRJXtqZ0wDA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
