apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qWKcUcKMhuqTruM+hJpkb+7WxA21HZKfaDWmt6cMe+EJ2NcLx9z6mwf4Rk5yT7cT81u0j2ciPLs+lZQM9BDKq76dMjcsDCZgPUm6xby2Wxvg0GGfgxP+3aZ4gEf/OWZkaoiiMbNGKZspUdIxFaOcdh5DpQgImrH5TxwXPQX0lNevQP2LpvWWGEfjFpwE2u8m7xfp35o/Rs51YsddbDX/qMEVfm2A3qi4qzaYTRFuM6o1i7HxzCr5gUP1AzKhbBgyxzhf1z8OviFDhLjKpUXtQU7GSsfijBDA1CIagLp279+7Haw37XFqposrUgEPM2YO5JgsIfdbcdCB4huSwjh6g/h4eE3WKhODwyiqRbWRCcivNtlgIbQUEwDzq+3A9Kwk,iv:GYTt+wwkbTIT0z3p0m6pJ/iZYPV6DQgJge0PYTemAjU=,tag:roc/henyYf8HvzeJAeA7nQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:laM2mYOHUoukVUvkYnmW35wZ8BM69hJl+gckTWe6CAYgy47i6096Lb+Lw82iqCTIQCankLbp7x4sxckqOPexl7EzlLhES/PJSuBDWFef6MS7QeS5QZw3oeeMw75Bf/VczIJrwoof6pAwYTWRLN74k+yqVAhsZQB994Q1w7xvsPgy8rJg+mAqyxhh3g3Uy+y8bxdel+5RG2UH3qd7oHxyuzqTGfas8Zo/buikcQ7WGNkcC0p5OrxNh3AP8tUx8n9da47Xb2EcKEzNJ1aonw==,iv:siRWo4hj9L3cccFF3/k0lHwWJpghAVbBVq+8hw2gg60=,tag:foN/M3XV5Z0a5KX4oiRmCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8VQb4+HTBHL/nGjT3bOE5r0h1XmDFVOSWlqXXxgov20vbAy0QWzHRplPe8pPmtvRurecXnpOLD5bJ748GcCYyFKpBeOINThPP04iyfjrWYOJGZ4OP7IVDN+d7iWUBuM4+Z7rAOXnvY+eWYiLsYJ/3qnSf9fTE4ZRyodZzN4GnNOslpCj5WETzXIDoONplnt6rxXXSemSa9VJxfqdh2aazE+reS0K6rcQeNao,iv:6GRtVqokExRqz/1lss4Lc768gaQ0rV1Dmg8xoEH8W28=,tag:TUBJs4BdWRDfOG9KJNGChQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNEE1enNVQm9GV3JIUS8x
            b0NRTW8zZ3JCd1hYOU1jeGU4RTJmRkhScFdvCnVjSDY2anFWQzk2WGRZdWFCTE85
            MlNlRzR2aW4xOTNISkMrdVh2V2ZBQXMKLS0tIEJLT0ovWlNycE9iYnVBcTRQM2lo
            aUlBMEc0aENJc3dYbFZEd3hIK2lHRTgKNplu80YNpU6ssmdVh2jEpog1p/SNqUNT
            C6JaRUDEEpkX4ImfUD0BnhZukXW6nIaEKXDAJtfjakGdOrlUqrh/og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T06:53:31Z"
    mac: ENC[AES256_GCM,data:/zHYlMjPgJapm93AYu5WWa/pa54gigCuzwXjSKAjefyby160a5pHoSWc0W/30Cz2BqFy/y5gJ23V2yFKrEudVDzRgg5SmBr+hKLcfJDLpca5ZNxcgsvwr2Iw4M2XBCeCVwXlgGKCU6ID1QIZWHHPNpRR8Fcq18tKAa4FqE0F3Gs=,iv:0RF/e9L0RtwLkTbev2IyrkyxAlkiKPEGABzyI5xek4s=,tag:MM4l1vt4rTbC/29pXPwxag==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
