apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5UDXfFqShUiSzPlDcye3joWpruK5vESyEwf9Z0NahAjlUm6kGkZhhaqcCUwSWDrF44E0Te+Y+7dnllZMf6ynhQOQaGVC78c2ttEwkdjoqSuQMrQY7MqUxH36m+hcWIvjmdvQf1tyXTTLpVdw9YDLr9yoy5f+V8/vzt4kKkMxuGW6fA1WiFVYpEBjLKcHl2N+Ab9VHB2vHPN1myPaS0MaTt6Y/cLi7h0eT0lqWpC4V5Gy0VyK8Sfz+ROCcy0GJivg49JUV/iqAPnJuDbSiOHmFDhHXrxwKbsR8oFStu6kw4ePrrrJNr+nn6EFjX3Cu+dvL7ybKEq60DsIX5J+4N6Xt4EfUhAPeHIk0Sr1OMNkCamPRdUnHWNquOv/s56ZqDeu,iv:SWwgX6QCNhANW3VtiYqzO+lPVYnFCsIQHA1bG/QIvOM=,tag:VU1K8MKJ5uJLPOl5eHToMw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hOPJx9mHhVm1xuzUgCRTHIibRF2JC+11+UGhkmLaB+6oWAjAt/xL4UiXS0MIAkPlFxnjwN6qQmSfp9LIh8NGLce1ZnsL9jRLBKeiWVTs6gKl/GwIO5Xjw6/OE/XeAjvNHKnPLPE5M/04ynJ0FaoPWS1jruuRgzqWdxhggmxW0uifFiGH2lP4ErHvgfIZZd5JmUGQ31O3Pexixrqyd0Mw2FSmWbXnsRmNWGiVzedXQXqBFOdojqIbP91TncTjk78WlMJZ2r1y0cwnhm70TA==,iv:XYKOvfVyEdfH94+1hll4TYpBNntbpJVorgmSOcE2NK0=,tag:C3YbtJmB0Rc6bNTceT2Buw==,type:str]
    known_hosts: ENC[AES256_GCM,data:2ZYo8n5s2E0nLf/Sqv5fw3EqCraZA9lxCgpBjy50tGfdtTQ9I19Zg6podW+o19PUHWneiIHtMEpn8BcLYTQlFU3ppdN8JH8sA1vvJdiAZcCXsDtjhNVzxcfQzUb6SpjA8WGzMXyKbm8ocSRG9zJhVtbqlgbizvDr3wSE7c27XAZcHoH2LH06Cl4kM+sR9h3hErvHwRHiLlHcs8pOogNp7rLBUEqjnzeM+2V5,iv:uJX2XzX2XsfH2ChxrSAafDVXPvF7M14RVy85wh451/E=,tag:98+aDd6uF8Qlxd1s1/h+mg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTEZ0VFU1djE1NG11SmtI
            bUV2Mjl0blJaNDYrTjJxTFF4bDJ2eEhqWFZjCkxoYjlKWm0zemlYdVlrTXMrNFZv
            MjRFdVU5WjYvYVVob1VQSlJIcWYwakUKLS0tIExhRy9kZXRZOEtkbXB1bndTUkJC
            ZXZxVWRYc1drc0tDWkt6Tm5USnYzUlUKrkqg4B4xt8yeVLTj5skyJMy817REbJ69
            0VFjCJekN2JVAQA6pbtxWpwIIReilKcUa2AZRTDfmHSliEqWW8OBVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T09:36:42Z"
    mac: ENC[AES256_GCM,data:n9kP7wHVmAVtedBJIHmRiySZ+PpVay3dduK3i6ofldMcQT/Qlmr5opyzMTjZYMz+dn/o+5axls3vrQoOvaiT9jCFgXHnvndhc4BNOvLgy7XSJPuvxe7kuIwpXqZ6GlYeOT2nGBOtzzg7R5uE2JhiqkmnRyJ5B54+WKAPAyqk3js=,iv:bUU+UQqt+EDyNX8fGhgUYFfimNQ+D8tpd2tWocCCy2Y=,tag:MKbNeWqxNcB7B74KX8JHgA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
