apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rJgKjmx+P70rUNRi9TXxvL/Hw3phdEyQqQ5nKb9jNHPEGn1E4bhzdmnp4qouBLYB+D4B7PwEWUEvFbJERcLZaTW543gEBLhf3Ln4HRQBjDVxblWjAopvgAyEo/iVMKmn5y5RtlYoHCslPmrxuz77tIkkAKXjJvGJdKFzZR/hItMpsvxc3lFt6/4cfXGRUplT2aH3ZPHHcFvK5xLYRE+U6iVxFt/glpiU1jVCZKbA7+6wTdMhVE+3GwhsI9DYbRbcSSSadi1GrkiONTrO1GCXK3q/er0eQOKaljB+j6TFGtrATk0+idAyx6cL5yK8MtPO97JAfFcIa3Iq3nhHwMiPf3yZq0lNFbZx0VM3rxwYetQZTWdB8L1UJ2rSxlYmk0Vj,iv:k4ClkK2/IDe+kvARFDYd/VLvq/9Equ8Ive2UIERIiV0=,tag:RGct1eLGK4teQAw4w28Xig==,type:str]
    identity.pub: ENC[AES256_GCM,data:/uMS+NoU76XvQIgUy+urZmn16bvCY2Je0MUDFXCPkBVlO6WPk4uD92akjZfEG1TUFXP+cfZTdrInK6gF82oqp644sNpbigvi67UBNr9ozgJy15VS5FqNvd2SKRUClQHt23OypgJy1r1yzD8BxAZpc/7nrkswRHmxgT0YCfHoIn7mfNk7mVu2VzjR4c2wNF+UXHf6lLCjThop578v1MJ1b2KG7PXB8GvkVOKWfkxN4YJG5FYFlTGrHp3mp9BHwNqUPRkHDCQNRseffhwHvA==,iv:i2RkpCEHxc/qkg0BjMK3eR3hzSIudXjFB1xdRaquTMM=,tag:ko/wyP1O4QGp0Z4TcInmUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:giAKSFGa5YcoBp4TrFzS8D5Zu7s3rFMbbLPRqkAAY5Do1OIgspQISfZDYRE0pMtde8YhMWK7tHM84HjGJ4mAYbHX+u0pKhzByZlMfRhH2lHU1FOjaPXTSx1SnXy/aWTnfPlcToxL2B/6PCOrjeHGUNqy4VIqKQ6BwXWPBJlrhXs0HhTOPkyFGHuqh9mHXI+Sy6TV8MNR2IK24ys5k8LGyHuslB3bvQHqWR9y,iv:nLpfvzCjD1inZYNKuUz/5woM3+zQcd8uQt0kjEnMnvM=,tag:SgQuhfmEuZtvVL5le/pW2w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwb2tIcVI4TkFScUIrOXRi
            dFFudGxXYmlVWDd6VnBnZnlJc1lFY2QvRUgwCjdFZ3RLZlNYcUc5L0VOYTY1UlBK
            S05NZWxaNTFWZldQMUxQQ3pkcEw5T0UKLS0tIElaU09EV2FoM1ZvTkJMTE5SS0V2
            ZjAxbWJWMDFYVElwU25DY1BmU0VLVnMKdmcV/KIt3Ng0ITP3vsaSR9DpTesn5EC1
            RYV1webmyMiARRFZClh/DB/vXMk4eOwKFJrvd1bPzYeKRM7mLJVVQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T15:33:54Z"
    mac: ENC[AES256_GCM,data:4tD0DYSBLnOpAJWkjqAxLztvt1tVG4LhRCbrIHKaZ1RYgyAB5gpkbDiwvpqH0ZVlvdB6ATJSHNyDs35L2cBMIOsHqdJg9Xs7XlvBpSbARSfhbYciLavh7mF42CDVTqQBdRSyXooD7UfjSYWGYJnQ6cJXWF4EFKiSbda5yfB95CY=,iv:jQFgusboh9SkaTisQ46gJXv0SsCSdhve0ns6AWFSH8Y=,tag:6e6miQsINMW2t3OUzZ6Rtw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
