apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tma6Ju8jvnt1jb5Bpyf5hgitCQmhgl4aJPxRhnQh+zd4EpzLWeLK6uJQy6eB3hb5IfeVFjZOylZ9PGwoRMn//OCJNCPTPeUPe0OzK2dYaWl5sqfma2gP4ZWplKVKlPEAGHRlbIAQCWAdS1mFW46U2RNvqReD3bMv75c6Mj2FtDNdJFIQ6Sir5W7JC+ymt2WwINHMwATpPF68R27HdLakCAdQFlFLbbx4HV8r3dUZ8/9A9k0GpuTZ1Kv6NBsyQUON0xKx79uF44DkguSpbzJ/IBSvOQESRWKnb3p2AmeK7TSa0uYbg9+EkJjbi3/zOFeDWi7H2dzvOBLDFyvyKB5sK/Yq8aZMkERXfwFpM6KwbV8BarCJ5gdd7OeKzuQAxZmC,iv:NwwhAFMk/5RvjzOL0aJeE2TuRQtiPBQfCqqayd/4iaI=,tag:e2W8EImMAEyYxgg2/eFhOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:b3QufL+rc8hPW4r9CWwaCq72u115fSpsMGh9cBpG46xiQmSt4Rj0G5bKOJijaANof3QXx2zGCkTqP6JD4c6499RUuHolzaZ+XCJ3JqBWiuw1X6CunggcN5tXafrpzLv3JqZVIfDGzE+DVhttlvSBLxsby2tqJ051JBnxyQNVerMN36/F76A964dssQZPSD08nROarqNOPhlWlq9/uN/2RzHfSZbWgz3BnqGOTzmW+V0y6gwWDnYikAGGXjnxHFtpj/Ix9g2rfMdjDBkKhA==,iv:877511l4lKlZnn310NlanTYV524/GWNQ8fOVoALCY/4=,tag:ppqXCHNsdRvUkDo+Nq1LlQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:r2cHmwVD/Z+XtjdDVOb+Bw4sVgvBWASRktxXLXvYnUN9wN21zoO0nq9vrgJMEghZz8Utg6g1K0T7R+Ab1dkv2zkaX56FMm1dkadS0yw1p11cURY3pTIRpB0P5wPpMq1dWjsASyN9NIn9Nr8OhZrT69/mxyvBVZbK4rCCJNvqP5hZK4+7Kex08/AaVg3UXLvzC4mD9m4nNLt5/+VjKV4A8XM1KkZstxVtoVog,iv:ewtYFslxZz6XF1k/bbpV9AL9/cjenQ43In/Zc+f1eSo=,tag:SLs3eRSDK3RpLo5lt+t9ug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MW4yRkRRSWN2N0FETWcz
            T2FvNExsZlhOVTdTWXdhTnBqbWpxQnY5VlJjCjhrMGVybzJoQlhPMEYrcERGSUlr
            Z0huMDhId2x6Y0o3S1BsODFES2xDWHMKLS0tIHRPcFcrYXR2dDdWZmxVWWs2MFNF
            TThsL0xRQjVDYitTZ2hVUEZodk81OW8KrnSmMyUohGbQVZ+TpSXzHsIq7aZlRtIZ
            Sn3p9TqggUSi7NoJz15awVU3P4bKbS41ox0B/6Vkn5xTEeL5n/yZUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T10:48:41Z"
    mac: ENC[AES256_GCM,data:EoxwFmeIHsVxNr/mraQDTBSchMx4eP1eX4zi53N+j72vt29gYlXupLL+ceZxT99iF18x4XcdDNZA9klHzbi0clfqD456p3w26ze1849/FmFvuYVHS+UXNOfuMONrVJc8prfdkwcaiFTbs0zzOcHA6zzYaaNnxM9V/GOMEyEO400=,iv:wL2cYGf7iFFwGtcyKoSrbPCoXqDx9F+RWgWs03UJqf8=,tag:GV3bxotXSu6c7XRt/68mdQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
