apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PXmLEChzucgNcBAtoIN4K+10e0ALBXcuKfTGUiUUQFrAeJky13xws3Qe45g/b9yt40tlHYm8Op1n6hQUtaWtShXeRRA9B2nbRSGj3AJXdW2MKkuOBfOva3o8DgFWmTb37lGzR7xlfO2NrfoIEwfozGOEW4EHDR0to737qWqOOwqAB6CRbKxEys+9i+82FLodJGQP3G6g+u3kXi6nV0cX/p+GJw3tb870fFVlPU0SdSKqIgz2AfoJ79rLeE7ibtj0KtxT2THAishVwBH5I+O6QegkjLaQSDVxVHIrHDeOgWW6HRiBobZJYhKeUCvbcCMcefOFG3MS45l1BYgK2NghwWG74SPagnTo7n9DOgrFwltP8ml1TOrthCsPkplEfRwF,iv:956Dm9c3jT7Rs5OccA0pCwzuKkYhVXTne9r2ZLs559I=,tag:wEttthzVSQ1EbOvwYwDxOg==,type:str]
    identity.pub: ENC[AES256_GCM,data:cfiFborvOF8zigbrVotqxuWgnjw5HK9p6hqwG+5da8ojrydScDxUesIG/tadCRZPGqNWT+6Esh4ulxa6Y6io1Z+iOcQFd14tSSL9sK78sdmhzx1x0iDAuawSu7zsxTpmmimXgUAwlK+esk2iEu1nClb1d9UksZQv73MO/kBHQIuG/nzrqKHAkuC26HT1aI6/0ELaj+6w2WED8eXERBRm/XkIno1BG4/HZhpSdNU5NRIIVZY4cg3e2Xb1B+LOByXEYERO/P6lAtbRbOQwrw==,iv:qV94F1YqKzDMBrePDjvOTj0NL7zEkxgvh+jr8JU2Gpk=,tag:hdL1t0ZDK66jzp8Co67v3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:lrWXYWyvfjDrFvQbS6jWL08QcYp+mJzXw8A2WF4cgg8w3Nautw2IRRMOLzBG9HZ2QvNbBFgV539U/CTStsLT0QOj+cGU7W0X2pbC89FmWjFc6M5coDlXqCtNMYKoBixngN1n3k09wzgsq+V7yV4Pd1RapUMkuOw0pvotCu6cteE3GVP9T8nXiPlT0C6uR6/cCtUzCaaI7bTNowv/TqGf0mnHLUlhzi1w9eFs,iv:y4btHpBTYRNQi5Xd1PSWzsMYO+ygpm5/35iU0qSNltw=,tag:qYbmtpXdMgNiG41WAKsS9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU2JGVGZlMWJCNWVHNFNa
            SWhVamdZYk9ra3E2NHBBa0J5bjNuV3pseTFnCmZFRDAvWEg2eFdNeDBNWG9TbHJl
            c3pFcFM4Q25xSWVjQVRqVmdNcFErU2cKLS0tIDhQUnBBMWU1QVhmS1k4aHZ4VTNp
            V0lvQ0NLRGh1UUNSQy94cFVsWnBTWDAKyY7FqJWsGqWSXzcpgW99ZnpEm1+1Ar3V
            8xZ7NBzGpGZmtqzrxLW2gn7QhFpcJ+tbf3JKPRLmcTzLmdL12MxHiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-29T17:39:05Z"
    mac: ENC[AES256_GCM,data:fif59wI/6rxzXYzi/+Jdqm5H1kaxkaqOBuqQp0M1HKzN2g4Umd3Txr2KeyM7d+lfT/bCeKutQbOcZl1eDdv7mAuTDODwSxlk5PlgjZTU5En17jvJKPZAQrHJJqNhzOK8Pz+OiyVmZ2AYQ1gXlpt68bFRZzT/dpCQebxJjrqNsz4=,iv:Q5wL5g/33sZpqePrJeYEZtc0oEYNM/h/62GR9Lt8qtY=,tag:aPHTdTNwcYfOiwuU/FJo0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
