apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vEuTDcLyIyblvDlUE4O/vKYOunrguMRFqnHemB3ihsa63JXUFS6tiFhd8kyQNQ8fYZ35kqjCxPcXICAXjwrEfm46Td3jhMkQrsm7nha8r/IIyi0w7Ae2fP+TX3QQ7OUlWKVm0+T3lVAHiupz2bijuSY+HlK+iPMHpq53CTRa1SffuA+rWG5WHe/bRv0eEWdHn+yh3kBBDwKU9OAu6Pex5T6iNwEhE/dfobDQPoRW743TTcaAL+WsBuXmZFXOzyXYkT6EwJgnjTLxsLIEqwqqsAxAYGxsOkY8Qhlf6OhP4Advf1DCMSGj15KanZqgYvHgppZMiA4PgPAprl7oj5LCMbB5/FCBoIOrFJK9dkfSypacO44lebRioSRqTlohRSiC,iv:nJ1QeXw1b6Cdp6PUfaUguIRUEp0u1BExkixFkcoKmMs=,tag:AUO1onzzIAx08zTDROG5fA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0ohMzQffWpRBAm4hrlc92IL54zjoYmAfkzB3umiX2ApTMeMGXTcgC6e80yPQ9lMRw0azAUv16wLrIRsIfUmjlu7/WMF8cm+w4Hz/subba3OrAv9aWHI7sgLyi/FWiwfNU72GBhEztk4iSsBWjcgnYKdMYNwU04rC4LTO7WuIdpo1qMXg4yQyglpYPA6u63dfMpszHWcIzyyF7Holc25tlLafMHGdfCbjDm71cuUUpF8hY6kLKaBEjUgCI68pjH6IOQGc+JXjVMgN7+d6Eg==,iv:IIBl6mmSRci8knohXyRfMtphn66teUrCu5URInonOhs=,tag:czBZI5s/jW+UcnfxuqfWZw==,type:str]
    known_hosts: ENC[AES256_GCM,data:v/iXkjNMa+YZ+NcX3WHTDVz1AzULkEqSiZKBejsC3+v9AB3iGvnU64z/NfcgR1n2qiFSDskb7erRGCGDBd4RucVBCukXU3+A7rk0n6GODKiCpTIAW9be95aoGENwygSlgq5eJrmlp3/eX4N9fQ1l8eMcNJsc2Dld2ay9ZIFi56mHIStE0LtVVoDBqAxVHO4o6EUuF5y4ufDk9uOY4NQY3PIngtLyFbQCZ8A9,iv:TIrDf31H2T+ekoxNYz3rkM4o8alKqlG+vUbi5ZNeWyg=,tag:6QV5rgdpAe6IoF78l+1dtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc0ZqYUsvbDNMOXhLOUYw
            NXFWbGh5MUkyaWY5dCtkdXAzSldUOU5YSFdnCmlVYWFxR1FSbWRDQVNJWlQ0Wm1M
            QThzMG5jVkYrV1NUNHQ3SWZEVEhJaWcKLS0tIE5rejhkS0tOcXJJMW5ZeS9VeFcr
            UXRBZUU4bHZNdjdHZ1pHY0lsTCt6VlUKt91EDkwfhu1/wAZLvvzIQF1mbx0Ezh6B
            qWsrei/lxd/GR8735tGkRuVYd13W9DSfRgp+E+7lajUg2hVt1o/i7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T10:54:09Z"
    mac: ENC[AES256_GCM,data:edoxv7DCaiy0WxDeTQAggyaVuXealhF64UEw21IQHPSSD30G3/4vbkmkou7zJH/SKnVGW64dDJoLJzbXYaURT992nEe7XyWMP24wF+M//UfZ7+Ky2NF+utFvqa98oFZXt4fRShez16JOXKTjzGlzIErMgiK9og54GXmJJBMgNgs=,iv:3n5Du7p8joWow4GTrmvz9lL8RVMEB4zjcWBYC23kgkk=,tag:KVSqM2d4wwK0U9TmLSQk8g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
