apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K1YK/Fe1/skCligY/VMg2xWWhtr8M7WrGOhjauzL44SkgZ/T3RLlBUvgwil5v0VV48j14Xuz+dwV6un35KGukxI3/FtD8NxAW/qL4+4RDxq7pBBfq6QoKm7av6XOoCQIc4XUZLBm8ctSncFJTvhSCle4zlumrRPFzYwQROzcV30T0TqpUOrhJx1QahNc2Ehml/XePvGKK/hg4Q3P9YyhJ5uICRfmPqTIuDpGHgtzLJmilUcMjH6K4Is3vnybtHoa9P8gg0PfckQ6zJ5RSx/yeW1PfX5lbh62SAaSF7EbT4xFvTqkHMiDZ41LkSnrxReLGHJE7GaGpKK8cZ9yR4ew76MuWA2qva26tROrgQfC8iByrcYUIKdWd5uWQChicSia,iv:Id8OBSCeh9/4jAdYfLirHXevRERcDS4DKwHnzMHKJsw=,tag:eDYCzR701XQzYBpnbLRIQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jI0egp1DQrevL4ayPDkQhEPH3r1rpItzL9JURwxxpOOtGNpbsciFuSuynY3WzEPnqKObtAtmoNNx2EPExZoqNZId9/nYwFMBxUB8rWyQxxfpTKX46bBV7N/YhacPFqmuq1V0V+XEewZu2KGaZ8BkBgO0hFotmAuRxLKcjoe4a4/E+BjzNL0sWqLYtoW5Et3UjiADzcHE8Yh6BMvpt9fLPuSGuwgRz0XRIQcMK2H4m/qgPQBRwLitt2rNFOUPZ71uAgzPrC7RKDi4aqdxTQ==,iv:zddBZQUSBBYXV8QteeD/Dxhxo6CLF6T/eC2AM9EG71U=,tag:T2JY9eOEpfLxggdKMtq62g==,type:str]
    known_hosts: ENC[AES256_GCM,data:cqxlZziDqoBO/mUMkqJ/35HXBy41djc5eDrjh5aeoY06G4Q8V82RBDJzlDuMqDEE4/pUiSkKbIjZcj0lCj9yvGmHR0s6oePLvhT0zjyqsSONTtt6sH9rsuvEBk+sG/aqF2hwn71YkvxJuKpkJV/j7hnvPO/JYhZXFhVncmUYg7vx9Q8FVH7+NxfyO65L4koyCB0JFzwxgG80NZZ2Z1tq5gdpVkrzsXT7MYv6,iv:k66UOgZX0sQc7m0JCeAZIuANgaUc0krH2WwLsM9Xgqw=,tag:aVrOhbK/L7pRf1v69fbhOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM3Fqalh4eGRiVDk3amcx
            bndHUDlFdmRNUFA4ZjJLZHJuUnFmbEg5b0JBCjk2Z2tGdDRPUHEwSzVFU3IzSUEx
            ODVaNVhaaGF4aTNHQW5nNUlscjBabVEKLS0tIFBreU5QeTRiclZFN25kaDBuNEU2
            K3Jyc3puVksxbmZxRFFzZGEwVSt2N2MKROkM7yaLVEOPrT3aIlhccAgZfEzOCSzH
            IoZWpXu0KLeU56eT6PEkO5M6s/zsPHmXIUtM+5zGpa+zJXtuUUCyfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T23:26:59Z"
    mac: ENC[AES256_GCM,data:MufePHFb9Nsj1M0wJ515nC6Fwld3vw8o+f5W7I9Z6c9A7kuDaxODaYR+xcXCBOxVoMZfNC0PlM1GhGt0ys1pl/GBgM2CdnFTrT1itGKYUAyuoy/0Pk64h9Z0RjNuLudQpOS/fPC7Yk9sqjSdfpxrQmDou+nfjL5ShzpUFTWvkXA=,iv:bLvAjtLCGZPGrJ5QXi36tWFLskX1m6aJ+9i7OMWlI3U=,tag:Y4+Petge0xxazJetivxPZg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
