apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vs7833ZO7vbfumJ6EK26JVJxwY7XWKR9cRKKGAKe+i4gNLFOgu1I0ErfqclfmBseFfabtxbbm6yftfFkQY0Ci94TlVA3448wrGLVq1VRuvblB6E/dYE5BF7AjsRap5yUZKxA9VycB6R5fRTYfEECUFqTSJSZUlHiI6mtUO2fuJIDSGUH0a2hHhdjFil6LIcFLA350KJu3WymOQLlYzULfyuhE7XAJYTXyTm6QH6hmw36FSjt+UITjT03iXp9CFIQViUa6THvNRjNgTuAmzY6lVTtpRUNV7fGcKULV6fXfXpVTUI638c9aoGvzSROKPBxVOgPfoHufNtWsGv5zk+bF3fCuGtNcZqmJc/KTuKUyW9UD/YwEIbPMT04ieXQUJfU,iv:4bnoXWXexb2qtqkp0gU6PtdH6cJuXyv0mQaY+BIk73k=,tag:8kfcY+OVOFqp+Vxkaw/15Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:UrW2G8gJAFmxJeVRaf9vnBpi0KlXWTQnW6QvxIFZUcwiC0zBXsTgMj7hNhhoLcdGqzICbKLYZDLQnyC+76x+gSZ7e34aS9p6pFFUBYSIzqlhC2X/Ap7IjcsOc2uvxxcfm5WaheUJoDDUAxZkPLjRjLi5baQXkK9dnrU2omB44r7tJXw3XJlQ3nG0wba4LFkdf/vTFgM0SRfkAoT8S3vV+pGxuYGEPFZngiaZ3wTDA2JQUbIuMsfYGFX2VpZp0dL5Oca9Lmdt5XqdNA+8Hw==,iv:K0J3d8scFPGr5+k3EXwPShExhys+4+ahBhozrb4hNns=,tag:78u5KOYyjaqJgmaczqN0uA==,type:str]
    known_hosts: ENC[AES256_GCM,data:5PY/GcSc6ZULfsJAswk2eO1knkC5QVYbFV9vmXF9VgiEBFf0fWP57kIL4ZKbcAiMiLQasrAN9PFyPwaK2f/PSSC26S5O6ZtEQ90d21vbqHxdAowBayiTLY9cMFQBgTnZ57oRHBPacCxGTwuVl2u0carGXveRqQMRhUM0n02F9w/JHoyQphpjvaw543lP1WjH2KQz4AxjXmLGV+1E916XE4vbEAw+t4dcvJm0,iv:ZoxiVgWSUZHkQXNBHH/1lH44EYOn6NS3lgWKgJQ10QE=,tag:P9BOAwWiEtEFR/BZPleSAw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RzVuK21mVGQ2c2JhdGY3
            WXduR3htaHNVL2RoN05UYkZ5VVg3OWtSQ3djClFjVGFpLzZXbTA3MWpEQkh1QXZp
            azhiSStMR2RsdVVpVUhEOEs3eGJqT0EKLS0tIDhVd1NrRXBHNy9rNi9HK1pNaUdO
            anhkOHhqVEtpN1QzbkUzdGREVS83bWMKbb6hB2jJdRuWGazZSuENqYhtR6ZspzCK
            LI9dCbZ0SKGFbpJ2SF5Lu8QjQ3w/1FGe/ORN22Q7Hv07ISyTFPzUnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T01:49:34Z"
    mac: ENC[AES256_GCM,data:O1M73AxIm6qLI5p3YvUol3A8j6COLb8Gin8avwVyLTbHbOPqmFHdABQVc4nQBX9G0JV3QiMPCK+k+iP/ed5mLnO4pqRCisWJjHRhttRA7cUG8Q3asBzxeJI6d1liolz6ohLOzCTf8pGlnSbBUzLviU14Llz0gBSFA6+ySG/e/XI=,iv:10Bncr0VvqEUfDRD98YIfvMQMmLCbKpYnMAUNeGyQKg=,tag:BXsviBZaxMxvHOljAddvXQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
