apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EuskDGyVdNGy2kcMwSUE/h7vUTBQXszzwqGpmJLvm1YLI+xb7l94+rdmsAw9aC0zV3dV3Gyz1egWCMjDl1R7AfDclAqjn45E0Ylt8MZNPb7fujvHq3Zp7gPLkST6U/65hdJMPu+d4Ql1NcVOmdTWVxW2poDXFoKiMVoGkhi1JiPioJQLs7UpwW66b42itRZsiYWDyp/pPedl4bFwpbueqq7eccfvEMZYwVfhEQThATPoy6IlH+3L9TZImYXAFWNZ4SwyHIGMSpNf/GuKnHtudGnHpcdMbi/DjkPYx2Ub0RvzPqwD3saQKUtJO7ncwR0lnAgkfMQACQ6IsyRP3wfGOIkZkWHzES53H8h31xyvYZex04bURYIO/HSk9qiCMHNY,iv:kjcRYq29OAGrM+4m+Xo1OGCQnFtsFbpL/ofi3jLpzEo=,tag:K8mBvOvZRVntX0ki5Pf8aw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1tnd6Il/wQB2sAwZUSkujHROBvU3Ta68/QAX1wIrZUcoeCO5OC7Xv1d8fBK+J9lyieGFMBYRt7GIrVcwiBRhOFh3+zVpQnX/ZYAN4Jk69eNvoR7dkkvthRP/uximkf031rTb5/SOaDSECGHohHHJ2e/HHVqsovjWm85cbPE9y796lBAxKTe9G3umtwpbMU1TBzSVUp2Cu9EK/ioUebT+gHoCQdYVKfQb8+3v0/qkK36jEB6SXsprQhHIb71cxfO4cmyWk01eYVT3+0algw==,iv:vIH4TVcUrc+YIKePreQ/gMnlH8lSfVP8TtNtWHU++dU=,tag:Y8i9BQ/cgf9754RZqO/cdw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PyIZ9zkuB/jl1bv6gry8on0RjK+65VelDiooYDfJJY/Cqtex62wHmExUGdo6aVhJ9Afd7KUKalU8aQntTecBBvMeEVcfo/2by25j7PvrdQkeWK+sW1umolYuLCEibpoWog93B9s5LuR/fnjGDrTzgxnyTXl/B1kaYMsrgnnwYALpYQD1jhTfqIniqX5SFAqG5u/tsR7LbNI0R/5bmOfP7eo8S/UMQEmkb2l5,iv:MOSwneecE53s6+hWeEyLXg/MEI++0Nquw0hJNt8I0qE=,tag:GWr/tH8rUUxiv7siXQGlBQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV21ZSzh1czRSdGV0Sk1S
            S0haN2VxeEdMeXBtUlhXQzE0ZXZhT3lVS0cwCkx6ZzVGTldVTjlQVUN3ZHl0YVR3
            TG9qL3lNOURjYjVWZDl6Mnl5VURRVzgKLS0tIHkvTE9rUnF4VkxZMDlpUSt2cDV6
            RTJrMWJIZi90OHhDL2o5dzN5U1A0ZVEKZMMkU6pCkGCWBkA309QNvwvelc0OjAj3
            eekUvMBUCnBAWPXDg/fZtxgWQ25EoetTrSyzfrp2nM8epbIHSPqMsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T04:58:11Z"
    mac: ENC[AES256_GCM,data:UQGjxFVG6L6+tR4IQaS4u2NCmoYVhH+FuopEpqn4DF5V7UhrcpLjWTkxfwgu2y/lw3Db9N1ldTspEsv1271Rinp618Vq3ymYbk0LvCn6w+r7+nva7bEWD326b1LkBhzGv/yNT4WW/j38uX+qc8Y5dqCouOUt833q0lL0uZgWrEQ=,iv:Hf4dzXaqaVpctIpkCqqLEjE5QRwFvbSGQE5lAjmqI+0=,tag:0IFQBuTWY5Cza1kMIN/K+g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
