apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:camsBLdOv6k6Ux9dgEygzy/XHt3VmST/s6GE40d+AQ1yDmUL9O+amX9fllncyqu040K7uhM74PgwDi1xX4G854TaodVd7dsoJqpUDSxjLwPew8o8efG7LLQDynXa9cEx97cdBpv7U5nSf+QZ6xy8pO410+PUOf25SG4Ub+fCi411MPiYfxgTwZOlMr8RyltleDYEJm3o9d91u++mihEqn0pFzeUB/+klxWjaESV9LowgjIHzHptj8D4QBDGQ8zilsExH9dLCqYyLtBv0HTj6qhep45bIcIQMfPl7Bx0mRnrAmBsqfkDe4D6UxwyWaeLstNtbwjSrC+abPrrfYByNQqrIGPLKuwgKyJsazkI+P+EqBgrQElmIqoI2UwDjVb3g,iv:7oD/dbwjeVBZpGKReJLKkWHANu5ILWsbVXfX/kMi+4k=,tag:OQhQa9Yby200JegOQGBxcw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Po4z6PSRQEJzT0Rq/lIy46s76zq+4ZspGb3Dmv9wCkjNuyahN+axQlKR73+pus4qOb5sfI+3OjFfHTXIsNBo+VZRBXYtBhoOpY/wC9eZ6Wwl1qKxo0Ru+oCqHTgtEMR1uE1hFnDH5nAx5Y8PUzMzy8/ib/1781wrkwWmnpAgXlT72UDOhnf8EPlSVAwb/9QrQyOjxPvsLjFI1CDY3r8l8kf7ghVVGIhy4EO3jCq1ZcMsAt2DWQ1HJEcRvFMSj61IikIwZRfMPKlTLNwteA==,iv:OeMoQCZwEfCpnLBnUz6dz6lYXdaaqyG6opHmWG4VeyM=,tag:3rIOn98Qy/xjAy3dlGj5tQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZvhkyBCn4sLT5OHvigFvOHKYFWC+ByQPWx9P/waefada2YFrYAovC4aBFxdQI6XcljPDxZCqtetWq4UD2kMamEU/np7PgGiFhiVaKCkuHZ2Phjtgd+26WvDQGBZM0Lwsy5EJbnXk1rMYhGVCtRhOeyG/65fRwACaQri9ntQrSfhQa8l7bbXx5pgFR5JsIgd3YafNi7vmrL6WjSMGEs64tf7PvcfZOm3BL5gh,iv:wbnvM7N3rHPnp2Vyvrco1YjrH64i6JtLEh619fLN67E=,tag:x7nUNJvOV5x9czXusVb1ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFT09NZTVFSmhrWG9USlA1
            TGE3bnlEQ0R6MElLSEhRQXhYV1N6dlVnSkRBClIydlVGNUNoWUVWZ01SalZFcWNK
            eGNlejFpS1ZCTWkvN28vdFRFZWhMK1UKLS0tIHJJMWwySU12ZVR4cGJpRTlXam1I
            SXJBdzZxMk94eHllaTBMM21FSG8yQncKcgA91ZdPQN43IqFBxV8WYDaNgN7Ydk/8
            0TzaVXyobwbTPBgmM8D/SE4LMnXq8wCYhU1QXJZLNkhjrQc3a3wO9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-03T07:29:49Z"
    mac: ENC[AES256_GCM,data:wNSbMR2uRnUUPBSAMdy3kWaRLLY9X4qZKdbapvufA4ltt9jzjydjeMlE2/XPninsfVF9/6E5tNZOcKLktrcmdTq3foMf+MI8NQKbsEh1ai+IPoSwQySGgvsEuJRh+1DwdAMKdYdAOeR95EkSpVGQidWFY7sCzY4cipwz7RBcVtk=,iv:FD4icKB54UzPS/MuSVz3vwfc14sxehyzSO9l39egYOA=,tag:/cbK2qRu5nRRonJds94oug==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
