apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wZeCoZc2B36R3XCTvGsqQwYVWFcrh2PvKtwLzUU3JpkJt6WacIAhxYsszwAN9LbIma85fVHbRL7VMMwrV8q5p4i/rnX5ZeNsgVerY6bRheQDq/IO5eSmUDgGVriJ0I8mo8y//JvNyPrWCGBgHGrk64mG2b6eDxTxjnr1BBmfWHgne4+OqXHdSW1wg+1F//i4F4epRnxaSfeGAHqRGCxlx61gIFuNr43QNpDp1Uw1iNrNtoJv66NdFX6TsFRlMPpEtjSoU8ELx9INe2n6/EdWY9ZmQ2Bp2M2/GuLh7JKuWvyvwkD+wYIO1Ef/icjcUIH9ElXiHsovOGZ8/m4TTh2prcPgAbBfJhyk4a/PDvF3b/Wut58CQI3ZzIHp5+XwlCBq,iv:9Vvcambf7tqfRGllpYwoMoGzH1cydMpgp2e9nXWwDMw=,tag:tznE+Qj9bAQp4r1p93egcQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:23wpE0mnH/kLrJKNrfrOlxIdcDHbr4a1CQFy/sqn0ZxxePOJfCbPeWx9jBZPmkSma+UcjzkDdQzH+qFx4nbKkga9jXaQVqWOFV7Gkh/Oi7S2X64TARRFW6LfE/gNNLk1BPG23ufvc2GDNc4jnDUNYkFv107y5WizmuLK+cEDVTsvQqdqAiiaxcCfa5IuAGqh36Vi9QYwvz0FwP/i7FDB7LKE9WBQZWBFO4ZYs+yitUzv/NrtzlYLYCM9UEDx6RRRZYMPBFWLyrojm5T9Nw==,iv:sq/yHarKD0l5gHtk3wXc509zkII+P4bv6PInTL4TPeY=,tag:pOPaVRq/+Bsgvrbw/xAJGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Nnt0IspIajOO6jb4wAqsrUg6jisRSIbLs280MUYEmP+iWIB0t6UBjp7W0l3hjm9IPIh/lNzcI4KFL7JUokO/iQJMywV+QTBY5XbsJ1/psJeCKbF0hPppIpt+RpJy+xUL9IJDlVMhzCoHfBy0zIv1bTPgPE2lNZSpo6iW8xXLuZlVAjQSbjE0Oo6nYVjKjJG+WdrP+E2IX3cOT0tiJDch4ABuNk5OYNo7+m1A,iv:kHjWRo78I7d46t1Fx1DZr+26s+i7yAJgFtdnJk2u+go=,tag:HBB7A7UNG+xbhQIVmigY1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbFJObGZaUmlYbFhxdnhD
            SkowbWlCblRSZmlUQ2RYMEZWWHFjSmR0Vm4wCnpkencrV2EvY2xjQUd4UHJadk1X
            NldEQkxMOEQrTXpBNE1lK1IwSlR5Uk0KLS0tIDF5Yk5Wczg0cmxsa0xwWDcwUFBw
            eTEwaE9EVUdXeDVIbG5VTVM4UmpabHcKDZxDSXTpGSRnbMK29mlWEj3ixRktY/0M
            TbriKLvvHUM8LIEhkj0T85PP9joViEbfqIj1TAHSF9aU/b3mrl0UlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T23:07:25Z"
    mac: ENC[AES256_GCM,data:7cUZB4jDvPs1APK2d0VLEG2WwAix+IsUoDh7RWGsWO1st3vb2x1LuAr1u4kleOojRp91TsetGqWjyr1G1bG5c+3YA5Z6/U7VyTTyCfwrsgKPHW8lDblCdLf2gkNf/so24ec3QGiqNSQRFR2SwciHdlI5rZXlw8mIKCzkz5W1jVk=,iv:Qc9EcnJR8UlHxoWnYeKVMypECjvQOfiId3G1PXzClQM=,tag:Q3Y3U8eEo+mRsoBIhiSf9Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
