apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ija4OAZaS6hREity+o5GX/oPv9pVSSuMnrr4Pa1tMXsfF4WhIyFm08HKDULq0eSG/SB02YJURys26BJh72v0bwAI6b1Ma3D39SLcL24s1zg2j9EBw/Fjdnh26w9upbz2OV8pzuJ26s0aBEDHFfaubYHnWwKr/1RgvdmONfis/KCuBUfWWSzd1i67C+KHEqJZ5msl+QcK6iEB82sIO7Rpdh/EdE297XdbuuLfVrFpNHa2yTmKMd/zPodq539rycy5KN3XTFzbFM3ovVgzYkYs1DM52g7vStgG6q10TFJNT9OP3DipyP4K7deHv3vqu83ytysN4Y2hOEJYdbSOleKnO1X6MXaTEYSJa53S8J7L37RwkdKIGnPJ6CXWz1ppixPN,iv:asouH6aYxVhpMm7scO3/QMBId+l3wjVngiI/XlMCxlM=,tag:ewwWGFM7y6bW5YPFRBuWow==,type:str]
    identity.pub: ENC[AES256_GCM,data:JBtJLX3K9F3L8ferSef4C0eubbepalh56Lxksgo4xQThnr/fhg5tg5i12rq5seSV+dHcHpTlYL04PXUb7Ra6n6rCxvVKIK1i09I4vNVKBtO64zXXS5TXPkUoskSrSDbNyC1eGopcslryTeQNEi1SqBXyqsgT7a5o21dWKACAVO9tH9+rjKB34x2K3jCsMdJczia+3t04j3oAs5dqf58d7KWAX5Di2O1XppS78++cEjcmzkqEAxsLzvyg6kHFBj+ZtpE8ue1bOROR2XEriA==,iv:0UMC8Enqa3lv6S203FMnyLhMXirOxx5UzP3UuCUokdg=,tag:mvnZM/cNDScWRNXPzMRcNQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:c0U7l3sNe3xEYeN92rmVNVudZo+p7H6cw3FRbE6u+Yqzz4kZcR5vmAuuaGBcb2MFekSrNr0wenkoJGxJufAZRVKdsCLS9SneA9x/i0ZWNEd5iyYKWjhKDENZyF5MsZHgOhHf+koO1K7/eEBiS0ft3vFDVCFzZiwW1Di4dQ0FTDaZbM2VCHvmXzGPh/LCYH5AEPNrWQ5xDW57oi3dmgaHAk0heflSvmlv/A6P,iv:pGIkj18P8OsV8kYxjTDjlFm9Kerf258e2WJzDJrbODs=,tag:TwT1NkCwkoL+XDh3T6aPrA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ2hTNXBBMXlVMTNvZkRo
            SDN3bWJuakhFY2YwSFV3ekUvMzFac3h5WEZFCmF3RndtLzdnSitUNXV5blRsSjFW
            U29nOUZMQ2tHVk5GRk1PZ1FHNHJ3MmsKLS0tIHFtK2JjUHAzV1VxTmxDd3QvSDdQ
            b0l1SXRFUzVzcXVTZEZvYzJsNFdrWUEKPcEOEm4iySXgaj2lae/Eo623MUooSE2B
            1r4fgHqJO9YqlAkyiNJ0M53GJzEjsl2w2lTuS3ClSD1/yC4u7aswBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T02:03:25Z"
    mac: ENC[AES256_GCM,data:8YA+TPLnTc6gaaDJZi7e3aS8uucA4soBrYJ2ZzXZ8RnuoK9zf4Gy4+rfpqX2Edti++vd7tv5d5DqfRiXqgg454jk4mDdZGG/S9KdKTlN06Mbs0ZxyelHkPJ/X+amkPBH5mB6627zwWRMRu9kNMJb5dK0RrMwl5DLvRjvSuMp0Qo=,iv:S4BCnmD4wtyc8WI9bmPlG0+GFFU/yH8B4+po4G/arp8=,tag:eHGoe9eHyZOt81t2iy610g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
