apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UmHMaC5rXeTNB5iihk4YDYAAngpBbhamNYPjqF09atZjEFVMv1g4ApkelQqZhl0TD/Mjmfqgk0njY4CRCZ4K/5s6+TlL/IbwYBzUzX2x9H5vEfwQSqZXoAhMqexTSnsZdAuZkZe1YuKLTCdxZtmuRHIBfELnl9JKyq3EE0AShxsFo+46C/ktd2xGE7sX/ZFCNy/jg5eUM2+fOmhgDmO6jpdlxj/+ldlWJS7X96zYFFCcuDMXAnO6bi6fgCRofLGwa7eu63WD0UnXRQpO86wOZflpy6TCEjGo8wLc7myhAbB4sfIGeaAEtQa/G/AVBoXjG72Hzuz/tPDPnVXqiRGswPa2azgGFvvNp+9NXyYK/gcTXyIHhh09LdNAi4hJmUPF,iv:QLCnPACTJgUVOtblFUTpg0wnUrnmWprEl3Ba/fJTPBU=,tag:RgkLoyNFeO+IP/yW71v+TQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZrI0gNCsQIuq+kWbQjDTMJaQc4BBkcD2WSV/UKF/41GMWNEAIwV4u1T04oOsftK5nnXPgE4HeHwssFSXNqJY2CBAm34yLdWXOGSuahkUmM3Qik1AkoX1IPn+PmyhufmEH2ZVc4fIAKihWWvk14F8+3NR733DsbfGPtVe+6Op2wdi/llfFzZRMKM9sEe31ZpNcjS/VBpxKnNTqWvCRxZHPVddYU75M9Hx9P3etJqFrkTh3yoFIOLy8PDNGlu19JrM99Iisis9fJ5deQaE1w==,iv:wxvFmm1cXvPdM6MSMLSL4Vl9vLLcw/cNqzczpjUQRcE=,tag:eW39IUPakFyvIXSUugsnlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:j36ovYxCZpKvp29mV5L89H2B2+8P2P15tWb3b4ddIQfwj1kAHIXESselXISJRTFQ6fdlMW2OqFZDtfEl1gmfxwOhZ29geWLFk4/TFWISpyjFbNg0EXXsYCxluAc0NmvQyx/AyzswCazxLQi8/Q4/1hdXHFJcCUCGnveP/5tjF51SV9mYWBurroOp0kP7m69RZIID8HJ91JLM/OinLgUHyQI1Dbdqfn5AH88y,iv:DEiqJLaiwZjppJJyjjcdsZHUvU3/CCHXPRGt8RaOW9E=,tag:Oi1n3Vq0vPxunRAyZY83Sg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRURxVmw4bmVqTkZHWG1t
            WEl6Q203TmdaMThMSkNEN1hGNTYyQk5DN2w4Cnh1bEtzS0JxMWFhRHk0c1laWDlL
            b3ZoT2dzZytaOUdjWWhnYVBRUDJDZFEKLS0tIGJiT3B5ZU5ZWlFWR3NyUnJLeW5u
            d1g4UVZyUnlWQ2pReGFrbjhBMVZXbWMKUWbQb3YUY9v/87t6bQgfpZunJ3k6JdUS
            U0ItxeSCytp3bAlQtIFmszKK2eFWZeumtarN9hlh9P/QvyfpB+sY8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T00:08:23Z"
    mac: ENC[AES256_GCM,data:t3N+hH8KzYo+HQm7KNLsOi79d3RSBbJIvg+L4SntdgqDLqIpBTvqs6JNP3o/c0NMR6qqp68F4CaEVf5N2AsJcW7meZFan1IVzqfo3nSMXNaFzxB4q0vg0dHRbbOYamOzyRMbDqLmA/G3S1e/Ck5pQAj6XaHZ/aWN14HhmxN9wE8=,iv:uKQ2JCR3njSxetxIBRVQ8pBYB5rQeVflbqpuoKFTmWQ=,tag:Y6N1tUKPoBn7haZx573+nQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
