apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dxNT/mTOAmoIS1Cb969HfhzRfr+uWzymWOjSOSCn/GwtszGHN1HdVIJzmS4Re4tedjj49/vsnHhksSdrisXzZ5CoKxe/Po0UNC3oC/U0uHx+ZHlJzETKbIf6zn8WlDhlckDPj8yl1r0d5R/mC1KVL/HKt421/t3WojIJG7ukSoPyysl4RgmxYfKFk0FOG0egfXBZonsi7uTgI23bnevNcgviw/8X7yRTZAcl9sYDrFtsUV3y5/ikhh8+L7PS8bCqlcOieDSkjue9rSpQ0zSOAoL2y27A3rPaOOdfYgzjW0sNoHAgVjcwVLUGCdX9NHk4X/b40/6iBdRnWj7RdQ3qI/zRcTINUWPQboc8uQMVrNCtl0FiinbuD/PjlA3ss/tk,iv:X6E55RXhMBn8p1fTGlHkz4CF0VnFvKx2mrn+SKU+LC0=,tag:dIebo6JzIhpbpRH91nN+Ng==,type:str]
    identity.pub: ENC[AES256_GCM,data:+c00ZubZ5ZWjfORDCL6Cl7BpfxpAhPunYHMB5AwctL3e/dUXb8XoLSIQqcoocJAk82rgTFKRynEouI/cJvixyXK04ocYLK7rsGGBlXbhaulsd3XfSmdA3rkHXANV/57B+HcPz8HiUHnpllvLPJqdzdlLcQBmB7UsM8PPi//xPDf7SS29/wat6nBTFVzIzje8YcQX0IwdVU32xC1Hjwm1zqao4wiq+dQavpke/49lcK7JD00pvHJdBKNL5XhcHXH2a8gs1ma5FF+57Y8+HQ==,iv:5025Wop/0f/ZCiWtoKAgQBj0kzs3pT+KbUPRz4B1P5A=,tag:c9AiwUObFf4PA0jmXmIxww==,type:str]
    known_hosts: ENC[AES256_GCM,data:1u8kb8TN+cG/u+PIGF+oADpa2hi7JQVQy/jTM1KzRKTo5rtaYCXlrFVOAzLCKjm1e88H0y2nU/x6avOcAa5uUlYZW+fz2v1LE//66QEavrgC6N3pCy7GJcT2WQouItu4a2rE+OgagJhiYetgbmzGrfrDGTI8wLKwDg2jvdrT9/CQYQIi331G6GkKw6xbD06OVIDvGrUTnkj+d4tGqagWbo3e0PD2IMwfdiwT,iv:tWWzxe6vcXZo4o0Qt3gS+Eo2YN8rUM2aiWyll5sq3ss=,tag:WCkL/0ejkslC2xdlNb9nOA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcUNqMTEzUmVSTTl5UUNK
            aVlXclhSRzNhSENMdmJFUVo4RmFpRUVPdTBZCitOSHcwRFpidHMyWklFWjVvTHhO
            eGlMdjNYNXdIazFLMnRjSm1KeGNBUkkKLS0tIHRBZG5PY0dvQTNnVGtkWmdMS2dT
            eU02TXpwZ2NST1l4VDZXWEdvdklzWWMKS3996DYIrXr5dIZbRSLiVGl/XG03eKS6
            3Enu0sU7WAORsLdwasbaOlcxz1ChZwYKVoFYbRFlDgRrNcnl20+/kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T03:04:34Z"
    mac: ENC[AES256_GCM,data:7tABrr0t1Vixf2Tj+eDPdR5Z7qNy+FgywlMxGe1s7gWoQk7R2S3ZofG02Kzg/0kr/GklzaWso8PxYABndspbIwr3wuLiQ3hJB8IxLS20il1Z90kjLlfZnAy/kREx4/6IQ0dVcqQmmttCgw8IIpItEJa0wEN3zTA7Enjw6fjLPbc=,iv:jjpvLfC1CK6jGMiRXIQgyFnv7Ekwb352UgiaPLfkrlE=,tag:J/zk2CQxZxgzqBzusjqIvA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
