apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Tkj9BKK/52CpbPY0dEyh1GiIldOxPthBqEOIsjc0ynsqSItjYetZ+NVz20F1rkQo7yz8Lvb7qojJEaShKOhVwmjXSeeGuTDElyRSG/gP+oblaxu+5BabcWe2gTV7AbrBGc1YIoFwnaX1LSlpLeeAz2aQz0uDJ/S4758u9CZpYCvjdZEBd7iTm/89bi65d9Ui0St0ta7dDdHpiow/+HXMR9tZZMz1tkpVXr+g7YNKF/uIFWzx3mbxZ+r+yuaB90m7xyckurIas8xQiO/xkTpH0/R20N1KAE0t1bjvM3+qMc5tqDWyXkhakVNbGylVLo9sreaQ16SmZ5Jxyg97SoVS4rjNGKnWSnB9+zQxpD2akLIVffBQYhQO3QGxB3Ohi1o4,iv:BN3RpLhpTgc2XGT5IJxpJ3SDSrdiEIEFCZyi8lvG6mc=,tag:Br5emRSJn7CkQkc4jcC1cQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Y4/LVoYgFdvrDrr26wTi3N7pWZTCzubGWcZo2T9DwxRTCI/Pj22MO9MBmzu0dRO/mPy7dQPtqWy27iCC2cVuDEFKr6I1fD9/o10c5H3J2zemNEvX6PghE1/N2shUrMSTBsOhAOgyfezWmZmKZ6nuXCmYhKKCfs+c3oiJ3ogYIGPvDbzeoeBocVRAsRWuRk6fp8PT6a6ceqp1MxLVVmuXjlZIxXP/2DYg7F0Ug3bXPe7HHbGwA2XUO5Bp4X4uOE22Dl6PCKuOhrQkhJITgQ==,iv:i+RfBrFT0oIhDLF0YMooxTbBbN5vNAdGdqREq9+iFA8=,tag:JqzZf+1DfIt/wXfbs1xXQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:C9CyKUf0xoOm5+r8crxujXwmt3WyLm6XJISB2V64Ao4l/XpD9C9w3/64RpUxkvoFzCx/o8y1cxC0ohxqLvgLZrOa3msnsrfRjsU0D+fKRzC6S4PmUkgbwkAt70UYnpjTZrQ4JdwHXd3z9dBiNYz7djnU1qM+ltBQHSah/Ks95qcOqJopj9X6x0puUL/5hOJ0zSaKjv9Qk8Z3iMnWjEJDfXlIe+GiWls/ddel,iv:zj7/ZVDNJNkvF8omuaHeyb1RPHKWFr7aYBJ7MC3aAG0=,tag:V8xUTmTEYcEprzGGrQ1XUg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeU5TWFlzekV0NnFaQm5w
            SWI4ak9WaVIwci9GTm01MWtraUFwNHZYeWg0Ci9PSGFXUVV6YUsyQTQwOGUyOU0v
            RFRaM2FmMjRmdHJiY2tzLzB1ZVJHK2cKLS0tIG84dVZyNE9ubXB5WnNOUTZvMHU1
            OUdPdC85RmlhWXpmVFJ1ZzBBbksvTGsKUrS8k/f+PHS3Gis9OAg6u97I8tenG4CE
            ubM0R/JQxeCAXtnYnRBhKFy3n1mJ/kafvqZgUTJM519vMPZeMLJgFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T01:22:16Z"
    mac: ENC[AES256_GCM,data:f0UYFqnIVma3hZiMIPLJTKCs7U9B65L5ljCaPDKRpHNfF8bXdUeW+uAl9s6jWSklGsrQwAMMoSnej+NBYbb3TziQ9WpvktSQwXrgyG7WT37B2G4OwadoJgN6hJWZ2qCMevAGxASSNYHdiPKVK4coG55F7AAUQ+vgXZINGk9KEiE=,iv:vNH1tcTHivZ6cQ0+d2WyTMzGpVtMiXPFYDeFK4Lr3OE=,tag:cOXDRKPViUJit/WLFLlIFg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
