apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8TbXK9pgpqfkpdU24GCtpMo8BEGFrGbXLOGAIWjoNopt5oec6BCdTGBjZbbTheLK8ZGOe/CKqPknIubWG8CoMRe5Tt0aboJ129Y+gwvru1iHcaXBDE2BToloo5jssv3yg3tUWlYb8z/2IxzMZ5iJTJxjAX0kMqFTkmcxBUFJcW6YshTJxtSLKtxFYFLMBXpBYoyLBmx3V/QcvKOH74UdtfSKNYkSqfKg6NZgnX468I1YQj8nQE46g+Rky7Mx//nmrjmJ/HbMPO5YbFia3Fqb1s/JoRWG6pTvO0J9Rq3pAtyYv+Zyv3mRoOH48aD+3t08Dyat3YmB0X8aVGOrj2ou/2QFdthfmFIv0Es9g6fNYDonnck5f0q8UbCcsDSZcjwA,iv:p4ownVjwpZ52kipTaJ/VVZKmnuhPG90lkUdUKyHDjPQ=,tag:cKqidz3Rz+mHR16CKtY7ug==,type:str]
    identity.pub: ENC[AES256_GCM,data:CYnmKLJu9z90z97iH9x5/vQZ2y582gVJnV9Q7W350mBnBYr/KSElSe80H33WJQMzoeDbQf7AlNPbVGO9ZVIt2h2dGppEafqoM8wRa7VY1U9FOayGQYGCRFPVy85Bo/c0Q5syHYmXcDkpt7r2Xflcvq74ad0ouVULtf94UJ8vbvUpzW/yVelfBbewAsEFZm9AWV+UuII9CKBLD0msFdQB/LOtnF/TOwHsEr54pZls+D1Ootq6W1NeU9Ibm2r7eNYxSWKMPawI77rEhIuj1w==,iv:PaKkf9L1BndAczvzdwHyiRXxtK5HXf1V3yCeGJPfmSo=,tag:wD42thuuJR19o1/09RAfYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:8lqv2vighL5mdKYmELB5dXI86wDXWxFDe9ds/EA89QQQODI2L0A4FipXuYhkuOnTghE0mpntWVmEMwpIzlmI0vsqmV6ouxbB+Di2OGimOuOqBznPHTFV25+WaaVGsuqsqPOz2b1hJd8NidifL3wsw4hfcy+OTh3Xo56EraFR5Nq9GlfnLocGSNC45szlDh3BJ3i0tuPPJsHTjcyzuAgbSiraTeocrChMBhxi,iv:bAuTvdk244PXfDQqgS0OpNdqw8Cb99zaHkRGpfLRZug=,tag:6sRtWSagNW5UxnLlj1M3Ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNEYvTGVzVCswT2ExMnYz
            OWIzZGJzSjdhYi9JZ0RRVit2VVBlSjFKaEJVCmk0My9DdXBoTVFYbHpWN1AvcTRv
            VkFEWnduYTRHRWdiVFY1L1dLaGpya0kKLS0tIHE3YXBmVWJDQ0ppNFdrSVlDTU1W
            ZXh4a0dKNzJSV0dhY3p5aDBLNWZsVFUKzcqHZs2R08VZSD/w472z2MzWMU5fGf9q
            7q9oJjp76EhxghwWKkQSv5veBeoFJfYLdXMXg+GiFbMJchzUuvqIPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T02:58:52Z"
    mac: ENC[AES256_GCM,data:Ryua1gi32TbnJurD3GTmslj+LhOjE04mrU+C/pM8lKcU8ZWtX34ZuoDLP0g4SqhJ+tRi4r2Zndf1kjmJyeXiSqZUO7SyKZqjrf5wBxtdLnyqGjdTn0ovV5n9NTQuGChCvps/xlgcsp7Q+UnmjxRbvdenru2eQpJoiRVEr83nayA=,iv:Tty7ItpU/uGUkZ693HP1ZSiryRiaF5gd1adGVM1/yXU=,tag:afh+7iKqniODFSt54UvSHw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
