apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CEE2WeKZdV2J7JGWM2LOnW5Q7CgV+gTMYTruloTyRiwsYk/rVapblt01ssnxGMkgJOtz1jLXGJm5F3BciaaMUtrFzolZFjvD2tDsZgCuqFi0XCIRdtux+aplG4X/PV9XlZ/O/P+SXxjy5fsBVtCAqfQ5ywi88+OBEmP72kr5mELgL+nUAOK58LPX5AqN1DrrekZQjcmRLVBva2SMi2gov8pPure0G7zN3bKv3WbW9jpSph8agsOzPbj4tU9KaW1jlAkGjpDbXRRry/9bLvzhldG3DdYcx0nn5L7WzLroGQ16rBswZSWYXBCAFVch48sZjbVRcS3NSeM2wVAZlZFs6yQGtqVhkpPCgl0aM94LdlxbhXBxgnrUZe/EaOsePgpg,iv:Y+AZpIRBkdYV9ZF96OZVqXRw5GR77qt6HXPRncMr+IM=,tag:65A4NYtoD8VF/1PQIX7Cxg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JQ+cg+EePeWGmZ99QEmrvg2Bb8mCI8RTnle+tw9h8pgJ9QbVCa/aNdXKbnnbSRfYIVL/1gSXcqRyY8UvhNBMPOX5ieTa+f0N5CqYwy21s/P+RXZnNo5W2lrd3uBPFYoi8/HCb0vlGv6vZfT01Kh/7d/DsuUtCm8y+cakT+PG59hghIbg8YfZHmNCmvs83fzBMu0QHTtHD1wBeEwD1/iewEVuexDsts2qUVbSVzAxhahpsv45QVRkjXfxiCnlCdslEYj4852zF1mvosCMOg==,iv:0bSFx4OTktxPgKUE71blEnoghxIHVwXgLQORNMbaiuM=,tag:gfiQQUdqiPywxwIRSP04Tw==,type:str]
    known_hosts: ENC[AES256_GCM,data:jctA9IEIZSSR92WVJafwsVNnHl8N2scen7c+p5X1VV29wGkWnBK1x/Xn5SKzpXyK2vsmTYzqTF/J+KUK6z9XP9NA4KDD0qUcGdnHUuInloyVHgnxeNDFQHOvmlWdHQ93ZG+s/eCIUZvnSlB+ZhlFb7E1iXW6H88FY+ygFPGIiuuxzgL6M/ML5WCXclLWWbeLZ77qnkUoU6U64hoSi+qdQTwsoPxfWrJ8uoLi,iv:iTymCDRvUmBC7hZzKLFkzxjP/ttMmmvl/R07SLfYL9A=,tag:Ht9KL7ykXlDub9RQQsPj3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU1RkdzR3bUs1R0RhaHNV
            SFdGNkVnSEhFZ0lDVm1GRVNzM2NKalRRa1VRCkMzSXcrNjRDT0VHUVdjMUpPbU9x
            K0FDM0oxTC90UndMMTFQVWRxY0l3NDgKLS0tIEVUWUNuRTZEY2Zybjg3dk8rOUIv
            bXlyMllueHYwS2lXalVrTHpvazlJOE0KTmT6Gnm62FtZFhzB4s2+FRyTFu4SKfUC
            UbhjFjn3gozfAWjpEnv1CxDxc8MA2vSGAw6Td69N0eq40XzIDXX2xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T02:54:30Z"
    mac: ENC[AES256_GCM,data:NLx0VPRkuwCWWbfLkay+72fhnQ31101GFvYr9O8Qjhr6qfAnR0LpA40ZbkQzXyKTFEg1bj3BTpul88+S1iOO3+cWG4SeFq4ELwittx84CEETbBZ+KdOPkH8Erjl+1FhZBD8I8F7hp2Q3MPY5w317GL82ScwD8APCsI3Gfz+0cMQ=,iv:IgfoNCNYam9GPitklnIR+L8ClvgRF3tV7SsZQ3t/Cz0=,tag:l5SaRGUBy5QKmiwJHoCeQg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
