apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qIxfFFcdB+iRIDuc6bWtTrUx6y1A4R+LlCtg9rvGpoYr7iLQDUKKtRa6uOkNGxAHGt45/Oc4XVyzRuhhW6PX0/6DUR124BeePDEKS31ur00JZHeHeMs/PB71HNW7FArd9FSaWZS3GuU5xAGbip4pBwFOOFPsjo+OyVu+etPwlyXPUJpl57J8v+A0OFcGuRFvgaUN2TkXxTekKfFx+GRthr3MAZ3rEhB3PXILab2Yxl4l+h41rJrjCq2eH/KuTNcw/CKR5kvobpH6AJ50SvHp+BmeO7SRpbqyzndjHPi9SXz5SDKr4LA+4RokRYYYWY9yTKOnRzVUUYrOsk+icdASk/DbJ+CCkMrs+R33ijLaq11P+IZMVIfaeejpnB5gjzxz,iv:nlEDyRML87ddeKTuHhtbjhZN9iOUciTbh+LmRAMGYTo=,tag:aHriUiC8sakFwAR0NghNSA==,type:str]
    identity.pub: ENC[AES256_GCM,data:mRLYguYabv6rxSXPn6xZcE+UMAE/89bZ5qkRIm6wVBt9P4H3vswcimMo646xeOiMU4pWPYLvOlWrwRO2alqGAixLfMtPxfRoTYrSz9Cf98Kyd4B+7pVEPCMfTNeEH+XaZ/8DiXaBwBXCLhagwJsdAwwtm2vqv2BwQt1eAb8//aUBZPVQyUdaLSb7dxccQQ7oujnZDzaWe0JR+FF2cSOhMGQMsx869VfbLFVvBLxTaT+QJWNedaaVxz3actxdRnf3xHLlZ9ZwEqAb2e0DhQ==,iv:jcOLB4hof/Ic5msJqSQ9S7ojZMC9YXgfEoKYlDUJ3Kk=,tag:uUu4eH+vQPCbbX41NW1iVA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Zci1JnCuXGrVVpTqRmxLE3wEiM0CZIYWL60doiHQZVIe8VVs7+knfrCGMSGARzRqpSf8jC3sxFGYLMy+ss/vW/ENwaC18NSkLEyYzKqXfLe3oVP25mG92g1OTCqGXXE4JJo8BhYcWrnKN65mRJa2xsFcRg3nuc0fkPwTc5QTkzn7z39rRVa8QQDThLxF1P2kzexHOawbX6T6GAiAsp2nZmi/RFiKuJzdInHJ,iv:CrSD4HzC3O7gw8McTeGeysk0bTtyQH/b0AVNGXvgQcI=,tag:W335bVpDgi1a0AsDbqZ0vg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNFpHTVMrSS8zN3NZSzRO
            K2picUY1YWJ0UDF4clpTQXJHVDNPaDR1NURNCkcvcHRWTU5ydWpCeWx1djJJWEh4
            cWlDSTNiV016Q3NNM0Nka0pUdnhTalEKLS0tIGRubk93QmxUT3pFeWVPVFZWYWd6
            Njg2OXZYOFlQanBBZjBPd25HdGw3cEUKbml3k7qjoqsr6xGccBur9q0VnBkkznOL
            aIpgBXiiQH59IwPQxagTQwLg5+kkEDqwUnByMX4BFNasw18x36ycHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T23:51:09Z"
    mac: ENC[AES256_GCM,data:r3PGEqcZRLhd0i1Ff7t5Mnzq6xSBGpuYXwq0F/BrCMrbwpR/wcuKocfnWawlrq5xudoPBY/Z5KJJ7oMOZAGBvczbbcq3RV7t24qSvnh59fT6oHInqcvtD/n7SrnsZ3nDvitksEzkhFBHOWTknx/7Fw3vJt4vHcBmlyGDuAzkXa4=,iv:gd6ieomyaS5+d8Dkm6LUonuoExaNA4tIKs/U/LHyuZg=,tag:geSX2W3VcVtd3dWLWvl8Ow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
