apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:niC/+dZ5Bl3mBpSDGaMUOztFDJLnj/PjrH+b19KLB0HrGcb5xVkPRHsXIRrWDDzivo2u3xhyHwVrUgoCSAEIgTwO3TgdIe2UP6Aml+YV2n8s5adl0ONJO/PqI40GoW4lhvkRWp1b/1hZnaICfMMVuZYHM/SIUrJHDnY3BJwo7XrtnlcSXGz43SKbsxzgW0ureeW/oV4f8Bg3x+btOnXOEA6AJJ1gRW+9x4xXfnbJjlmNS0pJsjPJIjGRfxLyGYr3EaJmBad+Dc5S0pB4ATo9VSSZewTq/OF2Bs6TvfqsyEklXr3CXD55atKk6MEMT/bqE1P96N1XQUkbWDcmd5UABHJuSTdOfkh3X2F4MpFq4O7Rk2C+L7tA0UfsblWTrigk,iv:p+mtOYpN0M/bP+mkLc/5DJVsDhLm3F4okmoSA7Sn/mg=,tag:eicTcOzeTDvONWR/2kS0Qg==,type:str]
    identity.pub: ENC[AES256_GCM,data:w1BEveb2rIWD04CWjLhC/nmVWKqrx9BNdGeyMH0nFHS7mPvUx+Y0Xh0V7L2tWRsqWTijdx4y5xIHameBXQe7nIB6rjiBv1qmq6XfAYfW6zMJvOQSs1OCONkQl65O4q1LYfaOq/HB7EciqueS0tGqtvbLZkViAi8Gj0KIEFaLgmEt/ndAa5Kc+050Y5Px14D9uoBb808MYIgMV1POIs6hlhLVsWIW++kGu033E8dMcQq/iUnfm8dun+7hGKTjsNyMyt2yLoatX3KcpyY6PA==,iv:t2ucaJsWua7w0erTXT0lPBi+yQRgvcPsteJ82rPKE3I=,tag:/WzzORrb+SUzCp1b1rAjvA==,type:str]
    known_hosts: ENC[AES256_GCM,data:n7xgdllxuZgyhccPqq86n//PK4JyktPS06X+y/O+k1SIdeNPfewHu3MQztBDNX7c7/9L1kVvf+YmdoTH/AgPZFf6cpCX4VpJit+M8bZwwOMSsALNPU7MX55MUKpM/Y7PGQeZ7RWXpcpzNmyEGrxeLukfmaMSYPCXYYa2C2HHYxoCR3HCFFHvvfLDKSjdWIJd4AjyGhteFaypBck0Cs4slRK9vpDrJWovLuU9,iv:5N7bWaIyGBV1SwhXMl5PEJwseErn+6vLurwZvcH4ybs=,tag:ESTfsX2sSjvWZuYqy5Uidg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRTR4M1ozTExuaDArOHkr
            Y0lKNlZCaXoyZ1ZGUlAzOEtyVDVVM0lSdkhjCldCWXJZWHNYd3NyMzF2UEIxLytj
            ZE8rQlV4ZTc3cDhXRUhKMTNDbERLTFkKLS0tIFFJcTVQS1RxWFQrSEdWb1BublAv
            T0NNOGxCNmtIVVBNUURlNWZVUDdlMVEKYspsaT4e8WVRcAqrlGgiLe5nuRtwm04c
            MWXX7FQEbhG1aRjHdlm0vKCshtXJ51ZbBEFaIed2gU/xriLjrHLVxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T20:59:04Z"
    mac: ENC[AES256_GCM,data:PnkNRykkw5nYpJCQnOWXhcDtnSZcK/wUFRu7T1tfWtJnFTWXlA+V0DaedejtUWQ7YkGuhVWJgIATLkm9MZ+QUAxk5gg2s6RFsYjVj7ANW6ISRdIvtvcl2kmHj5v5Ul2dAVSfuY1BTf+PINT2IcD+S5B+4v15znpMsg5xWUSWNvQ=,iv:BThxYCgAnNVe97UuBnwRMYrl11X3KQ96KwcZc0IMB+4=,tag:qeMqiEukuW1GqcIzrU8FLQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
