apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5l1WSShtb/r+792icMZsXjfARq4OOMGCWQw7gdlgzF8ZNaonS0xfyHXwKr8aYq5eKHR2b8v+ZrIAUCXIriVonoNQPnHMiQpDvy3+k22FJgqoaaubRgJMRGHUZfgv49LLFnGv+mpw7V1+vUENkzmtivhzUVBVtqhfHBEsXffXfSES+cDpd7n9oxZrn+a+R0/twdYGS6oHp0m6olOJ9GUy2eERah1lA7/9yudCQt3mPp5Bu/8jrzWijhUq+3w0UqBU5T1PawxkjFGEQxuFBstRXoScRn4EPR1X+vdgbxReRH8jsW2hot4uVA5e9sg9eaKlXhJzg3kDiKhyOn9d63QG54IVyWgdC1DZUF2s7aVzxOLGCZV6/Qm2cCSWFZfkPhYB,iv:AfW8RnwMRub9PPx0Zqd4tshZkvJR2nQBTJnrXRHwyCs=,tag:BtyVo+aRJL7q2k7bfW4mZA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7Z8jHnK2AiQwNgSrzg3Y6E374LbKUrmZvl5UfJf3M/noujnI4Bbd+lr44h1ojAjbkLqXkx6l8MEy0teQ157zC85w2z7EGD24Vvf1pKssaqBQ2ZgicqTHSXU+SdpbFlpjzX+x1R4aEZlWp/NgvgSsmixZzZzFVvIlSTEKpqpXqbFaUqsEbdje3SjkGf6sSCKyjz9Q8VJ+pz7tY0LBEF/EGPCn6vCgZOcjeohh6WDiPCkf4ylbFHC8+EiHCqsFvOIleuI8tRHvT3jcRugFRQ==,iv:+G4sUdf4g10jHS97Yfo5z9XgZeaBRSaoGTI1wAUM3FI=,tag:rYHX8468YSISqur6RH8nng==,type:str]
    known_hosts: ENC[AES256_GCM,data:F2d76uCbXtfq580pDoXfdvYm7uA5TJ9HIHmhIFBIIUKZywFF3ftzSY2Z2MqFntIQG+e5xf+zb+irYWPpR2SCEPtyc5dSFFWkavXHNrVd+0sg8Rx8MiJFeAV6/4KCPl1GueA7UOdWNYf7bye4Pd8/NW2l1o/S0ZcXxU/wZ5WzXI0taD1/yrKYdsakoznEfFcphHXqgMurw9MhqXJWaw8w3DRhl3hHQBJVtCIW,iv:/jonf29GngB9yfan51kEKmNZwuv71fFTh0hPd4twdec=,tag:O6TFkO4Zj4vFrHIOq/z2Vw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd2hncTlBUktEZmhHdFhP
            Wjg3bVVKTWxTVitReXRudy9rVnR2S0tiRnlVCnVXS2hxT29aK2w3amsvMm4wUmxB
            MGxmanpTTzB6eG5jdm40d3hKZ1J4WGcKLS0tIEM2ak93ZDEyaElEbUJCcG5hcjQ5
            bzlaWGlpVlBBcGlxLzloNERSRnUra0EKEBnlrFOOlHpdT/a+/PeEdXSX5URSX3cD
            PVunZali2B4Kfvyk4vXkknT+t1Tu7Gh4eY8lJpTsPpLPCC47DAd5NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T02:59:07Z"
    mac: ENC[AES256_GCM,data:jhGCOY6AQ1Rlo080xrEbBUdN1rcusZ+pzzHa4ft6VgrWBT1KXDlgqs2dsc4EiX4oGg+VlpPtZPg6UJjtCPy7X0n4ES3iGy49f2EPp3pXRv0iNjZ0quGEAKiLo98DlvEws+WOEqa+pyHVSY1/S9WpyuxHg4KbPvDWJWq5n0Vjgig=,iv:bmHDSs2jfvz0CfBcZbtDi9V8S9Fk3Tv6NNOPkTLUo1I=,tag:ovFA2v419VpkmVGQdKqJ9g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
