apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:88Xc8CDmSraqmAp3tXjj+OjbI7R7y4sruQpMRCsYLdIotA6II7EsujCBPKBQ+nxAY11r68AezgwhlAc1/WAX8MDtRG05XrT4w4KIwSJqvuy9lky8AYZuBWwExca3h4+VFMX/n1ZQR3B1wjeYOYbCoycKZTut9hB24tM2L+7p2NOeySklitafZuGb0dGRwIUKVMP2EIncDi24nmoeSV/7qQLT8moTV4lhcbHDLDjaEkG38lyUzq/ApZCCC4pBDZ76v76j6n8ScHBmmdLJDLc7pIOs/WNvO+827ji3oV+DjolAEfTvhsIqTyJsajdUdyT3aTycB992IxC5z/5lzMqUnLxleYTgVNVswt7MeLD/P0lwWSOlsxLD7JJd7s3Os9C7,iv:elg5HSkypXqzw63Jt3fta4gh6Ll+xx7hmG6pqr79Uhk=,tag:ciArbbrvQs6qnJhEjoCRzQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oCGBauiImesWlvwf2HwVcHdWgvnUL6uXXVhLPwm8GXYfjLYiO+yz193kaiZi8qv0NDOMvpGXk13dBGqNhllSMH2bvZi2bj9nD/3rA0VwuGMHaxp1XHDqtQdWgSD2ir3bayXQAE4UdwCyhN2eIzPjdxQ8qDa4M3otB7CdldPS4xWqI+8EzAbLk2tRbHgGLHVdriZR6N/ZefXBMvoVVuJz5+K7pm64uagKygZxPnJX7EmmCm8oWiI9UhByxf1I2tCjL02JQKOiSZWyUvcmKw==,iv:c25LBhBl8cRgC2q/5bORE3aj5pXs650b2Z+/K+v4r70=,tag:YfN4n4K68u09MfGt26dJ3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:3xJm7bbmmLaKwDIzyxS8FV8BDroFU/zsh2OyxjupS36Nb4dly7nZUPpzO6EfoxYSiFB0UKwVNRBwO8crFEKB+o0Wy0LznhveLGCxwTj4qhFBjtorSuLUJpXzpfNqtHMwTcl/D47gFTBumKpdLFUOMbiQ2oSuPXU1nwUsGPN3rUpSa2+upy9zMPFtR1f6rpdaM2h7tK0frrR/SqhSaJ0mfq7KcfRG9TIYXJUk,iv:kU6GXYVbvQUR3N1vln7ESUU6HtQ81LWtnRQ15Pr7u5I=,tag:puNkG17kPhrIQPGkiTKzfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y250WEc5U3JxMXBUUjBE
            d05uMnpLTTBCc2xHNUZRTU9ubFJwOHZwMGhNCjVGcXB0dHEwUFVmdjA4QnNvVEEw
            NXViMm1WZFlIZ1pJaENZYnZ1MGZSc1UKLS0tIEJkWEFINVBIdmN4YmhPUlppNTJ6
            bGlTQU5XS3BjSHBkYVlZU2Q0Qm1GTGcKDT3/JtKLmRzn4zQk6dc3GMy8FwMmLaX9
            1jbKyONu3XyfY63DwiaaAijX0bd5BzZD68eKY5NDxmO9A/u9ZbIM6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T03:42:51Z"
    mac: ENC[AES256_GCM,data:VAh+qxvYt18aWkiZMIlNuAVu4+BnltAn5J41OGr09+Bk+BuCCaISCJj6tB6QXdXLkjej+4OqEGfI36nBH7zUFGf7hoNmC5vjOdr/qtBQl50tbUx8d9n4hfEzSebmsUTlQKpQGzCl97D+XRx78ZewDNBSiCMwTC1a8aA0Be23sIE=,iv:bo810xqDknY/ECCSmFpZ0ESIuB4inP5gVBtaQ6JqyYE=,tag:WkZ1Yy7j4pMxWdX4ErRPuw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
