apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vHzbBR13p5WNB10681n07mauFa2zIA1v2k9js1MYf3gg+aZJZ3vJK4+FAWxXawGQQHgwJxmL4ZULsf0T3mHR5tPrkZJAhKdaMpwto+XSqKWbxsSknqva43e0ZScm6xLOmYB4wbcMhLcB4ixNugiNaNhlxfVjJsL7RWJ9HkwExvVCIeqIYrHMI3bF5ZtQ0XuePR2h60EhR1fnmXfWkEyk9199YH/6u5eQORl2qMm5oJ47dOz/C1fdKrYno4OF5qhsVZsW/XJFtbkOqyRlQYKtPRMpn49ghER9jA3lG3fv6i2kiYF+Cx5ENjz/EaX4oe51r6vQtxIz4DSlTTb3CKEQBflWXJODJPm6u1uTPfV8e6VRjQyXN+deWowrYK1S46Vc,iv:gY6nbduTLCnbOGtMkS2xZa+LAqg613M60QgJmjaNw1Y=,tag:3kC12hd2egVg8Ca0Rjx+0Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:H+Aer+82TAmu5ZsvQc1xuyPd4qOOCTklkkCgRUy6b+0gsT5dPJcAMVmWKL30pq5yXfcOEyyZeGmA3heBW1++n+rJ6XZiolrrb86o1MbmXc7UkPlJa59WAel5x2jRYlADEhGt4YJRnSKqQI61HCiEqr6AtmePOqxIgUGDvsUqyER8CPw8oSNMySE34xh4TgWtN/+9Cp2inmSw1sq0nfdO1PlmTS+lJdvfAsLq8t2jeOK7xyddvxo+LGlaJGghUaCSskoUs3R83O+FDM9o1w==,iv:sv6FAyI4Ob7Xs7dGvrcJfCALYjmaYxwj922h9j4bmFQ=,tag:0DWEKVLvsemODPhKlRkhpg==,type:str]
    known_hosts: ENC[AES256_GCM,data:0Z3rAeMs85TiAQkw+ML1umyfIzqUKCizc32oodBSF6Cqezq4x5eoJiT+tjZScpHG2PDuNr1uHhgCL/cn8Lt0cO7G1ORpg3YiDk69Xc/3Hd0m82rMPU82M2yNYl+hf4fVsfWg9MCukKBwsQiXtWGN8FgGhqsmCPoKMweQ/nMqvnSumE5Reu3K00UqkuorqJM0W262mcGG/DcpxF9+/r2VeIt8rEzr75FZFvUD,iv:Dovu4oW8KiLQ5FfMZmUpLefdroM00rub49/RpHbyoLk=,tag:98mrlSoUbhUStv5GHitl9Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdjdtMURtOVAxc1Z4WXl5
            Wkl1NXV5bkQrTVJEdnA5S28rUkowZ05GSFhRCnB5d3VjNUVjajFLUGxxUUIvTnBU
            b1p0YVBIR1UzMkM5bjZwMU1uQUdkd0EKLS0tIGpERGxhWklWaWV5eVdCMnBZU3NW
            bkxUUmJVQVU2azEwVUgvbGxPTk9UaW8Kh93F7tBiP/HLhzBuqmRcr2h3s5LjwM/k
            eKyu/+K5EcOKScjU+3CtGs1ZJ2lk/4AyIP0n7ucw2jB57OBdTDIFog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T02:01:24Z"
    mac: ENC[AES256_GCM,data:ZwgwDfJDV5JMII1LcKnKcz7UAYu4Df2zRLDbzwWl0b0lABTastt73i8wSjdtwstz6YL0MCswRcRbO/peOsOjU0WaSw9RFOXy/ZpbsAKE+0VpgqdFADh7ACLxu0narmNM84Edx7fRCuIUjHOgmcwMJYQ7VwSYculedq5N0ixJ12U=,iv:jReNYILrYGRNMSZoKTc6jWrqNPQaeFjpkMyqrLTgCP8=,tag:4FqJjWN0EDpAIfQZTrT1ug==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
