apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:cpszIjO+VBuX+1v6jFi6OhMocLmkhO2eOWHlp7WoV8pqLNGs+CZlVZ2NIiwaekggjkWF3fiEaV95SG2n3l/M6iTNaoTPHEcKGFe7QiL1c/tlgt6hPfkjECQhKkU66w7agUu90mxoErdp3topoEfjZd8Phn4tP2H1okl3RHxljW9Fwm1DzEjxuPENZbdgQvD/IERWN9RamIaSG18asJ1rbp2prFKWHv6CVvhB2uUucuO2Srp998H48V1VsXRM62+WhJq0WzXWDTDsN0zEmDnS1CbH/M2KfcaEGuXjQ4zKtb77mj3zMEFjsDYVQU3Ky1gdaJyASA0BtgYz5o6wNmXPI3ypa7HAu6k1DoQspWV6oBOuOBJ6JpjbNiEdER4beb4s,iv:JBCUzJaIhegLjDnBysk3YsltxVFdyKDkzpGRnWz25qE=,tag:qVVRmcptSUp751xzVWCGTw==,type:str]
    identity.pub: ENC[AES256_GCM,data:L2QyN26rEmyWEHN7TPrzhqfuILEkNUGeApzw2+5VddFkqG2OGXREhRSuaaBjpNqs8rLjYUQJj8HikgtzdWAVps2dfy5Wb/+blti9JEgZ6D06XQqWru63r9sJxM5qnDeAABhEtIdTWSrgoSN8REghZ2VERc2cvVq5zr0wpOsMTHFLhfvdn6eBQ8FY9alG0VrJa1usIVWu6k2OVXcGLsiH0zqk21Py05dGObC2LxhCNwVIG/8bmNeUTHcfJrG201+N7Mz3r92kxmjgvZb1Rw==,iv:fgR/G5qCutZS83Ad5VpyCzfCOrgKDWPtlahwjqdZ/dA=,tag:bIxmPg1c8oFpSm5XOlDaxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ziZCXLuxBr5wpHSmeKIKepOPSTbyPV1bTP94uyL/GnZIMsyU+ZaSzG1Gmblr5vaNVO57bVB586CEhfntJk1+FrSQbMKMcLGjVcTOkqqSUxM3bSp/Sp8+oevloW9mHcIY3HXYLBJCCFSkhPEyUoCRDM3/IS8GHb+TGRtg5rPWOFMJmCiAnk0iKyjaJ10sWr557k9jp92dEgHO+4IUoHFfC9qmLRcO/VcMpuAv,iv:cI1SngyA5HIEqQHOwfyoTD4pQWSXwHTjFzfjfoGUYdM=,tag:rwilO500lQenmkrFaed5OQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU2tpN0VJbzVKeGgyNlRI
            ZXJyRzJpUDNjK284LzZnS1lXWHc5VC8xK1MwCldyOWlzenlmcWxpZzlxS0owMll6
            SW5sNHgrWlVoelpwK3JlNHVjd2ZTdmsKLS0tIEM2WEF3WVNUd2FjVDlOVE9vY09M
            a1dMb3VVQnFaY3lWeXJFTzUzK3FWN1kKe2cZS9AmgpU0nr3+iDmptby9Td5nlAPK
            D4Ukl1sPkA4i9hnSHm2Z7/rBe6Ny1YrJEKcjZqTLNRXx4WGgZHbMYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T04:37:11Z"
    mac: ENC[AES256_GCM,data:8hHJ/2QhZNmsrBeb2Tgjz4h2cV+lkVFQjNg9/L0OZCchVlEHFvzSotr4LObbjxnTeQInWjRnCmeUSV6IaI0YQ1lJradMRggqYkmRWa1Kf6MJkg5dzw2dQgOiTwiyMfgcvQYcPmgUCXTkHGOEcj3lCS3A+XJcvBjTEu4Ot/1pW5o=,iv:16qxKLMnRFX1B1pChDkVEsN9ucDZW2Knm1aef8pvhPs=,tag:8Udo0nCO+Ff5cRLgJwURpA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
