apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7sN2WFXGytTfWBQ7yc1+0ApuI/JDDnd+vl+TsuYaI+01mf1sRd5RxX+qE6DRzhVisqWRb1q/LGpekpG/304pzrXriCs2ueVteQG7fSZkQIHbP/3CsCMZiY/3sbJkwPkPY8GLQ2iQRgdX57lQ8o9YiKtyUBY5I7RIbsogpR8wyDO4qGATup38DclO54kp0iS6H9LDJz1Z6bITVKYqKuos35O+t1ExC/lHyBYR2eYb39waJQGCfEC3zu58dPgyZnqKQqJM7RiKyjgB4r4I57FNQcwssbMKEsg4O7YP0aFUPOKIbT4eetEY9xBnJH5bqPzQchtjgGzLf4+hJhk0AWdQb2e35kd/3Z5CxhDVgJLMdQKiiYXgQ3x2hZGsY5ZST8sx,iv:oJ2UuVCUFfqfUH7Rbs2goAadPMokUAZV2gGX8HxJ3KA=,tag:MJ/aMS5zcUvrnY+rCXfY6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:QJz7tVRWsatYY+sDMuwUnCeUgKapsr+nd2ZWuIdbYGOWmyLUSkxJmbsO3iyBbA5hzrBqeu57l3DGO6UNzNVFoeur+hE7n7oWTSJmklLQLNtt+qcCPxXIghxE+nbdajH4u1fMZmHmlYbwhXMOJZ3D9JREOJ8jwLq4L4L9u2EvVksgwSUmBlIpqZy3B06DjQGK9tHjTy6qQoHv8eKzeX7tJDfck6tyQ7RiS78Rss1FkN7onyjYOPphwBXOy01pd6v7ltCqKIKq80Rhcaag1w==,iv:VnvVw0i0CCD1fbq/4xBvkQ+DmNc/vpuv7m47NpHckdo=,tag:xNyTMfGEYGI8Xa2rZBWDpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ncSj/KRYrUDYDa/78dyR1ZsX7IficRey9WwA57XnfpAlStW0coYbQaKVHkMTtP1szB0X3gjmUKY2haAZWtBiNmc2xOqmluGVSAFAnkIIgU7+CnSuM8yzuPP/ToRk7rFnWyG/QknT9NrDSsEAa22SZuPCo2ZFbSnqBjPhcYj/l9K5QjWv585BwHB61BDWfYwXPhMr3/orclZPxMLDMDFSxpc9viDj7XZGMOLD,iv:Ga47SKKnztBNO0MYfOB8QnYZuWKEovEq7ervjODeZoE=,tag:0e7N21BtUFmAiTK5t2WASA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ryes3cujp7m7su4qhk83rkra49szx824eqhnf9sw0j7u0wurv34ssaauzj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYjlZdjM5VUJvSVpGYmM4
            a3I0bS9NNHpMYTNUaTROK2RhUVlyc0d1MlhRCm9BVDh0OGpoR0RQMnNSRVRoajRH
            NXRqdkhYWnVsME5iTmxKM296RS9WVncKLS0tIGdyNUVIakY2c0pqZkFNTk1NL0Vt
            Q3JJNXZxcTRXeisrK1hNemorTUg2T1UKkAgnK2VRvV/hGWYTAe71kTu9cmnbK+O9
            +SBB3On0JDU8t6HDH5wO1ZjFjeit8Z36CfzM0XSZUGdxQickyVy4lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T00:43:48Z"
    mac: ENC[AES256_GCM,data:9+MmmIQa5jv1E4mU/HhQ49HVyw/f5SEaARTbfKN18YHtMzqHEf55E7nm/0CqXocDZyEcj7FCH4gcqs8mTIqT6cthOiLzwjLkctRwAYO0C5IQWwR4OSPVeRfilR6eFKTWUqw8aVQQ+DdLr0Y88HaK19MVr+gzGeQkbyqZefc5L30=,iv:iposJF5lnlYxkAYICGvq7mJ4baCksn2Dptfw/PQ9PaI=,tag:vSajOovOgBabTBXcDnCcHw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
