apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: wg-easy
    namespace: wg-easy
spec:
    interval: 15m
    chart:
        spec:
            chart: wg-easy
            version: 16.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: wg-easy
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            wg-easy:
                name: wg-easy
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        ingress:
            main:
                enabled: false
        persistence:
            config:
                enabled: true
                mountPath: /etc/wireguard
                readOnly: false
                size: "2Gi"
                storageClass: ""
                volsync:
                    - credentials: wg-easy
                      dest:
                        enabled: false
                      name: cfg
                      src:
                        enabled: true
                      type: restic
        podOptions:
            hostNetwork: true
        release_name: wg-easy
        resources: {}
        securityContext:
          container:
            PUID: 0
            UMASK: '0022'
            advanced: false
            capabilities:
            add:
                - NET_ADMIN
                - NET_RAW
                - SYS_MODULE
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            privileged: true
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                loadBalancerIP: "${SERVICES_IP}"
                ports:
                    main:
                        port: ${WG_UI_PORT}
                type: LoadBalancer
            vpn:
                enabled: true
                loadBalancerIP: "${SERVICES_IP}"
                ports:
                    vpn:
                        enabled: true
                        port: ${WG_VPN_PORT}
                        protocol: udp
                type: LoadBalancer
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                LANG: en
                                # PASSWORD: ${WG_PASSWORD}
                                PASSWORD_HASH: ${WG_PASSWORD_HASH}
                                PORT: '{{ .Values.service.main.ports.main.port }}'
                                UI_TRAFFIC_STATS: false
                                WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
                                WG_DEFAULT_ADDRESS: 10.8.0.x
                                WG_DEFAULT_DNS: ${WG_DNS_SERVER_ONE}, ${WG_DNS_SERVER_TWO}
                                WG_HOST: wg.${DOMAIN_0}
                                WG_MTU: 1420
                                WG_PERSISTENT_KEEPALIVE: 0
                                WG_PORT: '{{ .Values.service.vpn.ports.vpn.port }}'
                            probes:
                                liveness:
                                    type: tcp
                                readiness:
                                    type: tcp
                                startup:
                                    type: tcp
                replicas: 1
                type: Deployment
