---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    TZ: America/Los_Angeles
    logs:
      # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
      general:
        # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: ERROR
        # -- Set the format of General Logs to be either Common Log Format or JSON. For more information: https://doc.traefik.io/traefik/observability/logs/#format
        format: common
      access:
        enabled: true
    portal:
      open:
        enabled: true
        path: /dashboard/
    service:
      tcp:
        loadBalancerIP: ${IP_TRAEFIK}
    ## When bootstrap new cluster, comment complete ingress section.
    ingress:
      main:
        enabled: true
        hosts:
          - host: traefik.${DOMAIN_0}
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
              # - name: traefik-redirect
              #   namespace: traefik  
          homepage:
            href: https://{{  ( index .Values.ingress.main.hosts 0 ).host  }}/dashboard/
          # certManager:
          #   enabled: true
          #   certificateIssuer: cloudflare
    # middlewares:
    #   ipWhiteList:
    #     - name: local
    #       sourceRange:
    #         - 172.16.0.0/16
    #         - 172.17.0.0/16
    #         - 192.168.0.0/24
        # - name: github
        #   sourceRange:
        #     - 192.30.252.0/22
        #     - 185.199.108.0/22
        #     - 140.82.112.0/20
        #     - 143.55.64.0/20
        #     - 2a0a:a440::/29
        #     - 2606:50c0::/32
    defaultCertificate: "domain-0-wildcard"
