---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
          main:
            type: ClusterIP
          tcp:
            loadBalancerIP: ${TRAEFIK_IP}
            externalTrafficPolicy: Local
            ports:
              web:
                enabled: true
                port: 80
                protocol: http
                redirectTo: websecure
              websecure:
                enabled: true
                port: 443
                protocol: https
                # -- Configure (Forwarded Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers] Support
                forwardedHeaders:
                  enabled: true
                  # -- List of trusted IP and CIDR references
                  trustedIPs:
                    - 172.16.0.0/16
                    - 172.17.0.0/16
                    - 192.168.0.0/24
                    - 10.8.0.0/24
                  # -- Trust all forwarded headers
                  insecureMode: false
                  # -- Configure (Proxy Protocol Headers)[https://doc.traefik.io/traefik/routing/entrypoints/#proxyprotocol] Support
                proxyProtocol:
                  enabled: true
                  # -- Only IPs in trustedIPs will lead to remote client address replacement
                  trustedIPs: []
                  # -- Trust every incoming connection
                  insecureMode: false
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
        hosts:
          - host: traefik.${BASE_DOMAIN}
            paths:
              - path: /dashboard
                pathType: Prefix
              - path: /api
                pathType: Prefix          
    middlewares:
      ipWhiteList:
        - name: local
          sourceRange:
            - 172.16.0.0/16
            - 172.17.0.0/16
            - 192.168.0.0/24
            - 10.8.0.0/24
