apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: steam-headless
    namespace: steam-headless
spec:
    interval: 15m
    chart:
        spec:
            chart: steam-headless
            version: 5.2.9
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: steam-headless
    values:
        global:
            stopAll: true
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        credentials:
            steam-headless:
                name: steam-headless
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
        ingress:
            main:
                enabled: false
        persistence:
            home:
                enabled: true
                mountPath: /home/default        
                volsync:
                    - credentials: steam-headless
                      dest:
                        enabled: false
                      name: cfg
                      src:
                        enabled: true
                      type: restic
            games:
                enabled: true
                type: nfs
                mountPath: /mnt/games
                path: /mnt/PoolTwo/data/games
                server: ${MEDIA_LOCAL_NAS_IP}
            flatpak:
                enabled: true
                mountPath: /var/lib/flatpak
                volsync:
                    - credentials: steam-headless
                      dest:
                        enabled: false
                      name: cfg
                      src:
                        enabled: true
                      type: restic
        release_name: steam-headless
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                privileged: false
                readOnlyRootFilesystem: false
                runAsGroup: ${MEDIA_GROUP}
                runAsUser: ${MEDIA_USER}
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                enabled: true
                sharedKey: custom-shared-key
                loadBalancerIP: "${PLAYBACK_IP}"
                ports:
                    main:
                        port: 8083
                type: LoadBalancer