apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: jellyfin
    namespace: jellyfin
spec:
    interval: 15m
    chart:
        spec:
            chart: jellyfin
            version: 20.3.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: jellyfin
    values:
        TZ: America/Los_Angeles
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        autodiscovery:
            enabled: true
        credentials:
            jellyfin:
                name: jellyfin
                type: s3
                url: ${VOLSYNC_S3_URL}
                bucket: ${VOLSYNC_S3_BUCKET}
                accessKey: ${VOLSYNC_S3_ACCESSKEY}
                secretKey: ${VOLSYNC_S3_SECRETKEY}
                encrKey: ${VOLSYNC_S3_ENCKEY}
            ingress:
            main:
                enabled: true
                    hosts:
                        - host: tv.${DOMAIN_0}
                              traefik:
                    integrations:
                        traefik:
                            enabled: true
                            middlewares:
                            - name: local
                                namespace: traefik
        persistence:
            config:
                volsync:
                    - credentials: jellyfin
                      dest:
                        enabled: true
                      name: cfg
                      src:
                        enabled: false
                      type: restic
            # cache:
            #     enabled: true
            #     mountPath: /cache
            #     type: emptyDir
            # transcode:
            #     enabled: true
            #     mountPath: /config/transcodes
            #     readOnly: false
            #     storageClass: ""
            media-vol:
                enabled: true
                type: nfs
                mountPath: /data/media
                path: /mnt/PoolTwo/data/media
                server: ${MEDIA_LOCAL_NAS_IP}
        release_name: jellyfin
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                readOnlyRootFilesystem: false
                runAsGroup: ${MEDIA_GROUP}
                runAsUser: ${MEDIA_USER}
                hostNetwork: false
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            autodiscovery:
                enabled: true
                ports:
                    autodiscovery:
                        enabled: true
                        port: 7359
                        protocol: udp
                        targetPort: 7359
            main:
                enabled: true
                ports:
                    main:
                        port: 8096
                        targetPort: 8096
                type: LoadBalancer
        updated: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                JELLYFIN_PublishedServerUrl: '{{ $.Values.chartContext.appUrl }}'
                replicas: 1
                type: Deployment
